function mv_declareClassIdentifyObject(){mv_Map.Identifys=new MV.List;dojo.declare("MV.IdentifyObject",null,{recIds:[],Name:"",Headings:null,Status:"",VB:"",constructor:function(a){dojo.mixin(this,a);try{this.VB=this.data.selectSingleNode("ext").firstChild.nodeValue}catch(d){try{var c=this.data.selectSingleNode("lon").firstChild.nodeValue,b=this.data.selectSingleNode("lat").firstChild.nodeValue,c=mv_Map.getMapviewX(parseFloat(c)),b=mv_Map.getMapviewY(parseFloat(b));this.VB=new MV.Viewbox(new MV.Point(c,
b))}catch(e){}}try{this.recIds=mv_getRecIdsFromXMLFile(this.data.selectSingleNode("ts"),this.id)}catch(d){}this.setName()},getRecIds:function(){return this.recIds},getName:function(){return this.Name},setName:function(){return this.Name=this.Headings.setName(this.data)},getVBString:function(a){return"string"==typeof this.VB?""==this.VB?"":this.VB+","+a:this.VB.getVBString(a)},centerP:function(){return"string"!=typeof this.VB?this.VB.centerP():null},deleteMe:function(){1==mv_Map.Layers.item(this.themaId).IdentifyObj.DeleteRecInMap&&
null!=this.ele&&this.ele.parentNode.removeChild(this.ele)}})}
function mv_declareClassIdentifyTP(){dojo.declare("MV.IdentifyTP",[dijit.TitlePane,MV.ColorList],{id:"",tabContainer:"",pinned:!1,constructor:function(a){dojo.mixin(this,a);mv_Map.Identifys.addMe(this)},deleteItem:function(){dijit.byId("legch"+this.id)&&dijit.byId("legch"+this.id).destroy();"MV.RouteObject"==this.data.declaredClass&&mv_OSMNominatim.clearRoutingRec(this.id);this.destroy();mv_Map.Identifys.deleteItem(this.id)},toggle:function(){this.inherited(arguments);require(["dojo/query","dijit/registry"],
function(a,b){a("audio").forEach(function(a){a.pause()})});if(1==this.open){var a=dojo.query("audio",this.domNode);0<a.length&&a[0].play();this.flicker(!0,0)}}})}
function mv_declareClassIdentifyMW(){dojo.declare("MV.IdentifyMW",MV.ColorList,{id:"",constructor:function(a){dojo.mixin(this,a);mv_Map.Identifys.addMe(this)},clear:function(){dojo.byId("MVidentifyHint")&&(dojo.byId("MVidentifyHint").innerHTML="");mv_Map.Identifys.deleteItem(this.id)},deleteItem:function(){dijit.byId("legch"+this.id)&&dijit.byId("legch"+this.id).destroy();this.clear()}})}function mv_deleteIdentifyList(){0!=mv_Map.Identifys.length()&&mv_Map.Identifys.List[0].deleteItem()}
function mv_flickerIdentify(a,c){if(c){var b=mv_Map.Identifys.item(a);b.deleteMe();b.doFillRecArray()}mv_Map.Identifys.item(a).flicker(!0,0)}
function mv_identifyCheck(a,c){var b=mv_getIdentifySolution(c),d=mv_getThemaIdFromRecId(a),e=mv_Map.Layers.item(d),d=null;switch(b){case 0:"undefined"!==typeof dijit.byId(a)&&(d=dijit.byId(a),null!=d&&("categories"!=c&&(mv_closeTPs(mv_Map.Identifys),d.toggle(),dojo.byId(a).scrollIntoView(),"ClusterLayer"==e.Layertype&&0==d.data.appendNodeId.indexOf("cat")&&(b=d.data.appendNodeId,b=b.substring(0,b.indexOf("Container")),b=dijit.byId(b+"TP"),mv_categoriesTPOpen(b))),dijit.byId("MVtabContainer").selectChild(d.tabContainer)));
break;case 2:d=mv_Map.Identifys.item(a);null!=d&&d.flicker(!0,0);break;case 3:"undefined"!=typeof dijit.byId(a)&&(d=dijit.byId(a),null!=d&&d.bringToTop())}return d}function mv_identify(a,c){mv_Doc.IsMobile?setTimeout(function(){0!=mv_Map.WinMap.tapedTwice&&(mv_Map.WinMap.tapedTwice=0,mv_identify1(a,c))},200):mv_identify1(a,c)}
function mv_identify1(a,c){if(null!=mv_Map.MapPoint&&dojo.isObject(a)){var b=mv_Map.getMapPoint(a.clientX,a.clientY);if(mv_Map.MapPoint.x!=b.x&&mv_Map.MapPoint.y!=b.y)return}mv_Map.Pressed=!1;if(!mv_Doc.PrintStatus){dojo.isObject(a)?(mv_Map.Point=new MV.Point(a.clientX,a.clientY),a.preventDefault(),b=mv_getRecEle(a),b=mv_getRecId(b),-1!=b.indexOf("gpxmar")&&(b=b.substring(0,b.indexOf("gpxmar")),b=mv_Map.Root.getElementById(b),b=mv_getRecId(b))):b=a;var d=mv_identifyCheck(b,c);if(null!=d)return d;
var d=null,e=mv_getIdentifySolution(c),f=mv_getThemaIdFromRecId(b),f=mv_Map.Layers.item(f);switch(e){case 2:mv_Map.Identifys=new MV.List;break;case 3:0==f.IdentifyObj.FPMultiple&&mv_deleteTPs(mv_Map.Identifys)}f.XMLAccess?d=mv_identifyXML2(c,b):mv_identifyDB(b);return d}}function mv_getIdentifySolution(a){return mv_Doc.Solution?mv_Doc.Solution:"categories"==a?0:"smallscreen"==mv_getMediaScreen()?3:dojo.byId("MVtabContainer")?0:dojo.byId("MVidentifyContent")?2:3}
function mv_identifyClear(a,c,b){if("categories"!=a)switch(c){case 0:c=mv_Map.Layers.item(b);dijit.byId("MVtabContainer").selectChild(c.IdentifyObj.Container+"Container");mv_mapTipOut();switch(a){case "route":break;default:dojo.byId("MVidentifyHint")&&(dojo.byId("MVidentifyHint").innerHTML="")}break;case 2:dojo.byId("MVidentifyHint")&&(dojo.byId("MVidentifyHint").innerHTML=""),dojo.byId("MVidentifyClose")&&(dojo.byId("MVidentifyClose").innerHTML="")}}
function mv_getIdentifyParNode(a,c,b){switch(a){case 0:return mv_makeNode(c,"div",{});case 2:return c.getElementById("MVidentifyContainer");case 3:return mv_makeNode(c,"div",{})}}
function mv_addTopButton(a,c,b,d,e,f){var g=mv_getThemaIdFromRecId(e),h="",m=!1,l=mv_Map.Layers.item(g),k=f.getVBString(20);"ClusterLayer"==l.Layertype&&(m=!0);var l="mv_flickerIdentify('"+e+"',"+m+");",n="";""!=k&&(n="mv_zoomToExtent("+k+");");m="mv_print('"+e+"');";switch(c){case 0:h="mv_deleteTP('"+e+"');";break;case 2:h="mv_deleteIdentifyList();"}n+=l;mv_Doc.isSmartPhoneLayout()&&(n+="mv_Doc.setMapTab();",l+="mv_Doc.setMapTab();");mv_makeButton(b,d,mv_Doc.getText("Flicker","Highlight object"),
"fa fa-bolt MVfa-but",l);mv_makeButton(b,d,mv_Doc.getText("ZoomTo","Zoom to Object"),"fa fa-binoculars MVfa-but",n);3!=c&&"categories"!=a?(a=mv_makeButton(b,d,mv_Doc.getText("Close","Clear Selection"),"fa fa-times MVfa-but",h),a.setAttribute("style","float:right;")):mv_Doc.IsMobile&&(h="mv_deleteIdentifyList();",a=mv_makeButton(b,d,mv_Doc.getText("Close","close window"),"fa fa-times MVfa-but",h),a.setAttribute("style","float:right;"));null!=dojo.byId("MVtoolbar.print")&&0==mv_Doc.IsMobile&&mv_makeButton(b,
d,mv_Doc.getText("Print","Print"),"fa fa-print MVfa-but",m);(mv_Doc.IsMobile||mv_Doc.isSmartPhoneLayout())&&"MV.IdentifyObject"==f.declaredClass&&"WebMercator"==mv_Map.Projection&&(a="mv_zoomToDeviceLocation_Poi('"+k+"');",mv_makeButton(b,d,mv_Doc.getText("CurrentPositionToObject","Distance to POI"),"dijitMapViewIcon dijitMapViewIconDistanceLocationToPOI",a),"undefined"!==typeof mv_OSMNominatim&&(a=mv_Map.getRealMapX(parseFloat(k.split(",")[0])),k=mv_Map.getRealMapY(parseFloat(k.split(",")[2])),f=
mv_OSMNominatim.Texts.getText("routing.presentLocation","Present Location")+" -> "+f.getName(),a="mv_routeDeviceLocation_Poi("+k+","+a+",'"+f+"');",mv_makeButton(b,d,mv_Doc.getText("RouteToObject","Route to POI"),"dijitMapViewIcon dijitMapViewIconRouteLocationToPOI",a)));"function"==typeof mv_userButtonsInIdentifyWin&&mv_userButtonsInIdentifyWin(b,d,g,e);return b}
function mv_insertInDocument(a,c,b){var d=mv_getIdentifySolution(a),e=0;null!=mv_Map.Layers.getLayerObj("MV.MarkerClusters")&&(e=1);"categories"==a&&(e=2);"route"==a&&(e=0);var f=b.getName(),g=b.getRecIds(),h=!1;"MV.GPXTrk"==b.declaredClass&&(h=!0);var m=mv_Map.Layers.item(b.themaId),l=m.SVGLayerProp.StyleProp,k=null;switch(d){case 0:d=!0;2==e&&(d=!1);k=new MV.IdentifyTP({tabContainer:m.getIdentifyContainer(),title:f,open:d,doCopy:h,doFlicker:!1,recIds:g,prop:l,id:b.id,data:b});k.set("content",c);
dojo.byId(b.appendNodeId).appendChild(k.domNode);k.startup();0==e&&(mv_closeTPs(mv_Map.Identifys),k.toggle());break;case 2:k=new MV.IdentifyMW({doCopy:h,recIds:g,prop:l,doFlicker:!0,id:b.id,data:b});break;case 3:var n=mv_makeNode(document,"div",{});dojo.byId("MVidentifyFPContainer").appendChild(n);var p=mv_Map.CurrentExt.Width/2,q=mv_Map.CurrentExt.Height/2;mv_Map.Point&&(p=mv_Map.Point.x,q=mv_Map.Point.y);var r="position:absolute;top:"+(30+q)+"px;left:"+(30+p)+"px;width:auto;height:auto;visibility:hidden;z-index:4;";
require(["dojo/_base/declare","dojo/_base/lang","dojox/layout/FloatingPane"],function(d,e,k){d("MV.IdentifyFP",[k,MV.ColorList],{"-chains-":{close:"after"},closable:mv_Doc.IsMobile?!1:!0,dockable:!1,resizable:!1,constructor:function(a,b){e.mixin(this,a);mv_Map.Identifys.addMe(this)},close:function(){mv_Map.Identifys.deleteItem(this.id)},deleteItem:function(){this.destroy();mv_Map.Identifys.deleteItem(this.id)},init2:function(){this.flicker(!0,0);var b=30+p,d=30+q,c=!1;p+this.content.clientWidth>mv_Map.CurrentExt.Width&&
(b=p-this.content.clientWidth-30,c=!0);q+this.content.clientHeight>=mv_Map.CurrentExt.Height&&(d=Math.max(mv_Map.MapOrigin.y,q-this.content.clientHeight),c=!0);1==c&&this.set("style","top:"+d+"px;left:"+b+"px;");"chart"==a?this.set("style","min-width:350px;width:auto;height:auto"):this.set("style","width:auto;height:auto")}});d=new MV.IdentifyFP({title:f,doCopy:h,recIds:g,prop:l,id:b.id,data:b,style:r,content:c},n);d.startup();d.show();d.init2();d.bringToTop()})}return k}
function mv_identifyXML2(a,c){var b=null;if("gpx"!=a)return b=mv_identifyXML3(a,c);var d=!1,e=mv_getDataObj(c,a),f=null;if("MV.GPXTrk"==e.declaredClass){if(e.Analyses.Wikipedia||e.Analyses.Departure)d=!0;f=mv_GPXModul.CountryInfo}1==d&&null!=f?(null==mv_Doc.Para&&(mv_Doc.Para=[]),mv_Doc.Para.push([a,c]),mv_geonamesFindNearby(e)):b=mv_identifyXML3(a,c);return b}
function mv_identifyXML3(a,c){var b=null,b=mv_getDataObj(c,a);if(null==b)return null;var d=mv_getThemaIdFromRecId(c),d=mv_Map.Layers.item(d);b.appendNodeId=d.getTPAppendNode(a);return b=mv_identifyXML4(b,a,c)}
function mv_identifyXML4(a,c,b){var d=mv_getThemaIdFromRecId(b),e=mv_getIdentifySolution(c),f=document;mv_identifyClear(c,e,d);var g=mv_getIdentifyParNode(e,f,!1);g.innerHTML="";try{mv_Map.Layers.item(d)}catch(h){}g=mv_addTopButton(c,e,g,f,b,a);"gpx"==c&&"MV.GPXTrk"==a.declaredClass&&(g=mv_addWikiButtons(g,f,a,d,b));mv_identifyXML5(a,g,f,!1);return mv_insertInDocument(c,g,a)}
function mv_getDataObj(a,c){var b=null,b=mv_getTableIdFromRecId(a);switch(c){case "pano":-1!==a.indexOf("g",a.length-1)&&(a=a.substr(0,a.length-1));b=mv_XMLFileArray[b].item(a);break;case "wiki":b=mv_XMLFileArray[b].item(a);break;case "gpx":b=mv_XMLFileArray[b].item(a);break;case "route":b=mv_XMLFileArray[b].item(a);break;case "user":b=mv_XMLFileArray[b].item(a);break;default:var b=mv_loadAttrTableFile(b,!1),d=b.getRecord(a),b=mv_getDataObjXML(b,a,d,c)}return b}
function mv_getDataObjXML(a,c,b,d){var e=mv_getThemaIdFromRecId(c);a=new MV.IdentifyObject({id:c,themaId:e,data:b,Status:d,Headings:a.Headings});null!=a.getRecIds()&&1<a.getRecIds().length&&(c=mv_Map.Layers.item(e),c.isTiled()&&c.TileRules.getSpecificTiles(e,a.getRecIds()));return a}
function mv_identifyXML5(a,c,b,d){switch(a.Status){case "pano":c=mv_makeIdentifyPanoramioNode(c,b,d,a);break;case "wiki":c=mv_makeIdentifyWikiNode(c,b,d,a);break;case "gpx":c=mv_makeIdentifyGPXNode(c,b,d,a);break;case "route":c=mv_makeIdentifyRouteNode(c,b,d,a);break;case "chart":(new mv_Timer).setTimeout("mv_makeIdentifyChartNode",1E3,c,b,a,d);break;case "list":c=mv_makeIdentifyListNode(c,b,d,a);break;case "categories":c=mv_makeIdentifyListNode(c,b,d,a);break;case "user":c=mv_makeIdentifyXMLFeedNode(c,
b,d,a)}return c}
function mv_makeIdentifyListNode(a,c,b,d){var e,f=mv_makeNode(c,"table",{"class":"identify"}),g=mv_Map.Layers.item(d.themaId),h=2;g.IdentifyObj.ShowHeadings||(h=1);b&&(b=mv_makeNode(c,"tr",{}),e=mv_makeFullNode(c,"th",{"class":"identify",colspan:h},d.getName()),mv_appendNode(e,b,f));if(null!=d.data){b=d.data.selectSingleNode("c");try{var m=d.data.selectSingleNode("Im").firstChild.nodeValue.split(",");for(e=0;e<m.length;e++)mv_writeTRTDs(c,f,{"class":"identifyPic",colspan:h},[[m[e],!0,!0,""]])}catch(n){}h=
d.Headings.getHeadings();for(m=0;m<h.length;m++){var l=h[m];for(e=0;e<b.childNodes.length;e++){var k=b.childNodes.item(e);if(1==k.nodeType&&k.nodeName==l.NodeName){e="";k.hasChildNodes()&&(e=k.firstChild.nodeValue);1==l.HasDefault&&l.DefValue==e&&(e=l.DefSubst);0==g.IdentifyObj.ShowHeadings&&""!=e&&(e=l.TextPrefix+e);if(""!=e){if("number"==l.Datatype)try{e=Number(e).toLocaleString(mv_Doc.Language,{maximumFractionDigits:15})}catch(n){}e=[e,!0,!0,""]}g.IdentifyObj.ShowHeadings?mv_writeTRTDs(c,f,{"class":"identify"},
[l.Alias,e]):""!=e&&mv_writeTRTDs(c,f,{"class":"identify"},[e]);break}}}null!=d.data&&null!=d.data.selectSingleNode("TL")&&(g=mv_getXMLNodeValue(d.data,"TL",""),1==mv_relateCheckData(d.themaId,g)[0]&&(e=["js:parent.mv_showRelateTable('"+d.themaId+"','"+g+"');"+mv_Doc.getText("Hyperlink","Further Data")+"",!0,!0,""],mv_writeTRTDs(c,f,{"class":"identify"},["",e])))}else mv_writeTRTDs(c,f,{"class":"identify"},[mv_Doc.getText("QueryNoRec","No records selected."),""]);a.appendChild(f);return a}
function mv_relateCheckData(a,c){var b=mv_loadAttrTableFile(a+"link",!1);return null==b?[!1,null]:mv_Map.Layers.item(a).XMLAccess?(b=b.queryTableLink(c),mv_oExists(b)&0<b.length?[!0,b]:[!1,null]):[!0,null]}function mv_showRelateTable(a,c){var b=mv_Map.Layers.item(a);if(b.XMLAccess){var d=a+"link",e=mv_relateCheckData(a,c);1==e[0]&&mv_selRecords2(b.XMLAccess,e[1],d,a,!1,!0,!1,20,!1)}else mv_showRelateTableDB(a,c)}
function mv_makeIdentifyListLinkNode(a,c,b,d){var e,f=a+"link";null==mv_XMLFileArray[f]&&(mv_XMLFileArray[f]=new MV.XMLFile(f));if(null==mv_XMLFileArray[f])return!1;c=mv_XMLFileArray[f].queryTableLink(c);if(null!=c&&0<c.length){a=mv_XMLFileArray[f].count();e=mv_makeFullNode(d,"h1",{"class":"identify"},mv_XMLFileArray[f].Name);b.appendChild(e);e=mv_makeFullNode(d,"p",{"class":"identify"},c.length+mv_Doc.getText("QueryRec1"," of ")+a+mv_Doc.getText("QueryRec2"," records selected:"));b.appendChild(e);
a=mv_makeNode(d,"table",{"class":"identify"});f=mv_XMLFileArray[f].getHeadings();e=mv_writeTH(d,f,"identify");a.appendChild(e);for(var g=0;g<c.length;g++){e=c[g];var h=!1;0==g%2&&(h=!0);e=mv_writeRec(d,e,f,!1,"",h,{"class":"identify"});a.appendChild(e)}b.appendChild(a)}b.innerHTML+="";return b}
function mv_printIdentifys(a,c,b,d){var e=a.document;0<c.length()&&(e.getElementById("MVidentifyContainer").parentNode.style.display="block");mv_Doc.Para=[];for(var f=0;f<c.length();f++){var g=c.item(f),h=mv_Map.Layers.item(g.data.themaId);h.XMLAccess?d=mv_identifyXML5(g.data,d,e,!0):""==h.DB.HandleIdentifyContent?mv_makeIdentifyListNodeDB(d,e,g.data,!0):(mv_Doc.Para.push([!0,d,e,g.data]),mv_makeIdentifyListNodeStart(eval(h.DB.HandleIdentifyContent)));switch(g.data.declaredClass){case "MV.RouteObject":mv_Doc.Para=
[a,g.data.ele,g.data.themaId,b],mv_checkPrintMapLoaded()}g=mv_makeFullNode(e,"p",{},"");d.appendChild(g);d.innerHTML+=""}};