function mv_declareClassTracking(){dojo.declare("MV.Tracking",null,{DoDraw:!1,Index:0,SelektionAll:null,Symbol:null,StartTime:null,Distance:0,GNode:null,PathNode:null,PathString:"",OffIndex:0,RecCountDown:0,TimeSegment:0,Slope:0,Intercept:0,SIDistance:0,FromP:null,FromRecP:null,Point:null,RecId:"",constructor:function(a,b,c,d,e,f){this.id=a;this.TimeField=b;this.OffIndex=c;this.TimeStep=d;this.TimeMode=e;this.DrawMode=f;this.AnimButton=dijit.byId("MVsliderAnimation");b=mv_Map.Layers.getLayerByType("TrackingRootLayer");
null!=b&&(b=mv_Map.Root.getElementById(b.id),c=mv_makeLayerNode(a,!0),b.appendChild(c),b=new MV.Layer(a,{InLegend:!1,Layertype:"TrackingLayer"}),b.SVGLayerProp.MinScale=1,b.SVGLayerProp.MaxScale=1E12,b.SVGLayerProp.ScaleEle="",b.SVGLayerProp.StyleProp="stroke",dojo.byId("MVAnimationDiv").style.display="inline",null==mv_XMLFileArray[this.id]&&(mv_XMLFileArray[this.id]=new MV.XMLFile(this.id)),this.Extent=mv_XMLFileArray[this.id].getNode("tracking/ext").firstChild.nodeValue.split(","),b.LayerObj=this)},
initSlider:function(){mv_declareClassSlider();var a=mv_XMLFileArray[this.id].getNode("tracking/slider"),b=parseInt(mv_getXMLAttrValue(a,"min","0")),c=parseInt(mv_getXMLAttrValue(a,"max","0")),a=mv_getXMLAttrValue(a,"labels","").split(",");mv_sliderCreate(b,c,a,this.id);mv_Slider.slider.value=this.Index;mv_Slider.slider.increment(0)},setTimeStepComboBox:function(){var a=dojo.byId("MVTrackingTimestep");switch(this.TimeStep){case 1:a.selectedIndex=3;break;case 10:a.selectedIndex=2;break;case 100:a.selectedIndex=
1;break;case 1E3:a.selectedIndex=0}},reset:function(a){mv_removeSVGele(this.id+"TRLayer");this.GNode=mv_makeSVGNode(mv_Map.Root,"g",{id:this.id+"TRLayer"});mv_Map.Root.getElementById(this.id).appendChild(this.GNode)},clearSingle:function(){mv_removeSVGele(this.id+"rec")},stop:function(){this.DoDraw=!1;this.toggle(!1)},toggle:function(a){this.AnimButton.attr("iconClass",a?"dijitAnimIcon dijitAnimIconStop":"dijitAnimIcon dijitAnimIconPlay");this.AnimButton.checked=a},initTable:function(){if(null==this.SelektionAll){var a=
mv_loadAttrTableFile(this.id,!0);null!=a&&(this.SelektionAll=a.getRecords(),this.initTrack())}},zumToExtent:function(){mv_zoomToExtent(this.Extent[0],this.Extent[1],this.Extent[2],this.Extent[3],20)},initTrack:function(){if(null==this.Symbol){var a=mv_XMLFileArray[this.id],b=mv_getXMLSubNode(a.getNode("tracking/sym/mrk").firstChild);this.Symbol=new MV.XMLSymbol(b);this.PathSymbol=new MV.XMLSymbol(a.getNode("tracking/sym/trk/path"));this.StartTime=this.getTime(this.SelektionAll[0])}},initPath:function(){mv_removeSVGele(this.id+
"TRpath");this.PathString="M "+this.Point.x+" "+this.Point.y+"L "+this.Point.x+" "+this.Point.y;this.PathNode=this.PathSymbol.makeSVGNode(mv_Map.Root,mv_Map.LegMapKoeff/mv_Map.Scale,{id:this.id+"TRpath",d:this.PathString});mv_Map.Root.getElementById(this.id).appendChild(this.PathNode)},initDistance:function(){this.Distance=0;this.FromRecP=this.FromP=this.Point},draw:function(){if(0==this.AnimButton.checked)this.stop();else{this.reset();this.DoDraw=!0;this.toggle(!0);this.initTable();if(0==this.Index||
this.Index==this.SelektionAll.length)this.Index=0,this.Point=new MV.Point(this.SelektionAll[0]),this.initPath(),this.initDistance(),mv_Slider.slider.reset();this.AktTime=this.getTime(this.SelektionAll[this.Index]);mv_Doc.Para=[this];"realInterval"==this.TimeMode?mv_trackingDrawEqualTimeStep():mv_trackingDraw()}},createSlopeInterceptForm:function(a){this.FromRecP.equal(a)?this.Intercept=this.SIDistance=this.Slope=0:(this.Slope=0!=a.x-this.FromRecP.x?(a.y-this.FromRecP.y)/(a.x-this.FromRecP.x):0,this.Intercept=
this.FromRecP.y-this.Slope*this.FromRecP.x,this.SIDistance=0!=this.RecCountDown?(a.x-this.FromRecP.x)/this.RecCountDown:0)},getPointFromForm:function(a){a=this.FromRecP.x-this.SIDistance*a;return a==this.FromRecP.x?this.FromRecP:new MV.Point(a,a*this.Slope+this.Intercept)},drawRec:function(a){this.initTable();this.Index=a;a=mv_XMLFileArray[this.id].getRecord(this.id+"rec"+(this.Index+this.OffIndex));null!=a&&(this.reset(),this.Point=new MV.Point(a),this.AktTime=this.getTime(a),this.drawNode(this.DoDraw,
!1),this.drawPathFromStart(this.Index),"realInterval"==this.TimeMode&&(this.RecCountDown=0))},drawNode:function(a,b){var c=this.RecId;"single"==this.DrawMode&&1==a&&(this.clearSingle(),c=this.id+"rec");c=this.Symbol.makeSVGNode(mv_Map.Root,mv_Map.LegMapKoeff/mv_Map.Scale,{id:c,cx:this.Point.x,cy:this.Point.y});this.GNode.appendChild(c);b&&(0==this.Point.equal(this.FromP)?(this.PathString=this.PathString+"L"+this.Point.x+" "+this.Point.y,this.PathNode.setAttributeNS(null,"d",this.PathString),this.PartDist=
this.getLoc(this.Point).distance(this.getFromP(!0),!0),this.Distance+=this.PartDist,this.FromP=this.Point):this.PartDist=0)},drawPathFromStart:function(a){var b=this.SelektionAll[0];this.Point=new MV.Point(b);this.initPath();this.initDistance();for(var b=this.Point,c=1;c<=a;c++){b=this.SelektionAll[c];b=new MV.Point(b);this.PathString=this.PathString+"L"+b.x+" "+b.y;var d=this.getLoc(b);this.Distance+=d.distance(this.getFromP(!0),!0);this.FromP=b}this.Point=b;this.PathNode.setAttributeNS(null,"d",
this.PathString);this.writeText(this.getInfo(!0,!0,!1))},getLoc:function(a){return new MV.Point(mv_Map.getRealMapX(a.x),mv_Map.getRealMapY(a.y))},getFromP:function(a){return a?this.getLoc(this.FromP):this.FromP},getTime:function(a){a=a.selectSingleNode("c/"+this.TimeField).firstChild.nodeValue;return mv_timeStampToDate(a,"T")},getTimeDiff:function(){var a=Math.abs(this.AktTime-this.StartTime),a=Math.floor(a/1E3),a=a-this.RecCountDown,b="";60>a||(3600>a?b=Math.floor(a/60)+" "+mv_Doc.getText("min",
"min"):(b=Math.floor(a/3600)+" "+mv_Doc.getText("hour","h"),a%=3600,b=b+" "+Math.floor(a/60)+" "+mv_Doc.getText("min","min")),a%=60);"realInterval"==this.TimeMode&&(b=b+" "+a+" "+mv_Doc.getText("sec","s"));return b},getInfo:function(a,b,c,d){var e="";a&&(e=this.getTimeDiff());b&&(e=e+" : "+(this.Distance*mv_Map.DispUnit).toFixed(mv_Map.DispUnitPrecision)+" "+mv_Doc.getText("UnitLength",""));c&&(e=d?e+" | "+mv_Doc.Texts.average_speed+" "+(36E5*this.Distance/Math.abs(this.AktTime-this.StartTime)*mv_Map.DispUnit).toFixed(mv_Map.DispUnitPrecision)+
" "+mv_Doc.getText("speed",""):e+" : "+(this.getSpeed()*mv_Map.DispUnit).toFixed(mv_Map.DispUnitPrecision)+" "+mv_Doc.getText("speed",""));return e},getSpeed:function(){return 0==this.TimeSegment?0:"realInterval"==this.TimeMode?3600*this.PartDist:3600*this.PartDist/this.TimeSegment},writeText:function(a){dojo.byId("MVtoolbar.textbox")&&(dojo.byId("MVtoolbar.textbox").value=a)}})}
function mv_trackingDrawEqualTimeStep(){if(0!=mv_Doc.Para[0].DoDraw){mv_Doc.Para[0].drawNode(!0,!0);mv_Doc.Para[0].writeText(mv_Doc.Para[0].getInfo(!0,!0,!0,!1));var a=mv_Doc.Para[0].TimeStep;if(mv_Doc.Para[0].Index==mv_Doc.Para[0].SelektionAll.length&&0>=mv_Doc.Para[0].RecCountDown)mv_Doc.Para[0].toggle(!1),mv_Doc.Para[0].writeText(mv_Doc.Para[0].getInfo(!0,!0,!0,!0));else{if(0>=mv_Doc.Para[0].RecCountDown){var b=mv_Doc.Para[0].SelektionAll[mv_Doc.Para[0].Index],c=mv_Doc.Para[0].getTime(b);mv_Doc.Para[0].TimeSegment=
Math.round(Math.abs(c-mv_Doc.Para[0].AktTime)/1E3);mv_Doc.Para[0].AktTime=c;mv_Doc.Para[0].RecCountDown=mv_Doc.Para[0].TimeSegment;0==mv_Doc.Para[0].RecCountDown&&(a=0);mv_Doc.Para[0].Index++;c=new MV.Point(b);mv_Doc.Para[0].createSlopeInterceptForm(c);mv_Doc.Para[0].RecId=b.getAttribute("id");mv_Doc.Para[0].FromRecP=c;mv_Slider.slider.increment(1)}mv_Doc.Para[0].Point=mv_Doc.Para[0].getPointFromForm(mv_Doc.Para[0].RecCountDown);--mv_Doc.Para[0].RecCountDown;window.setTimeout("mv_trackingDrawEqualTimeStep()",
a)}}}
function mv_trackingDraw(){if(0!=mv_Doc.Para[0].DoDraw)if(mv_Doc.Para[0].drawNode(!0,!0),mv_Doc.Para[0].writeText(mv_Doc.Para[0].getInfo(!0,!0,!0,!1)),mv_Doc.Para[0].Index==mv_Doc.Para[0].SelektionAll.length)mv_Doc.Para[0].toggle(!1),mv_Doc.Para[0].writeText(mv_Doc.Para[0].getInfo(!0,!0,!0,!0));else{var a=mv_Doc.Para[0].SelektionAll[mv_Doc.Para[0].Index],b=mv_Doc.Para[0].getTime(a);mv_Doc.Para[0].TimeSegment=Math.floor(Math.abs(b-mv_Doc.Para[0].AktTime)/1E3);mv_Doc.Para[0].AktTime=b;b=mv_Doc.Para[0].TimeStep;mv_Doc.Para[0].RecId=
a.getAttribute("id");mv_Doc.Para[0].Point=new MV.Point(a);mv_Slider.slider.increment(1);mv_Doc.Para[0].Index++;window.setTimeout("mv_trackingDraw()",b)}}function mv_trackingStartAnim(a){a=document.getElementById("MVlistTrackingObject");a=mv_Map.Layers.item(a.options[a.selectedIndex].value);null==a&&mv_trackingInit(themaId);a.LayerObj.draw()}
function mv_trackingSelect(a){var b=mv_Map.Layers.item(a);null==b&&mv_trackingInit(a);b=mv_Map.Layers.item(a);try{mv_Doc.Para[0].stop()}catch(c){}b.LayerObj.initSlider();b.LayerObj.zumToExtent();b.LayerObj.setTimeStepComboBox()}function mv_trackingTimeStep(a){var b=dojo.byId("MVlistTrackingObject"),b=mv_Map.Layers.item(b.options[b.selectedIndex].value);null!=b.LayerObj&&(b.LayerObj.TimeStep=parseInt(a))}
function mv_declareClassMarkerClusters(){dojo.declare("MV.MarkerClusters",null,{GridSize:150,Clusters:new MV.List,Symbols:[],IsInit:!1,HasMoreInOne:!1,Event:"identify",ClusterRecords:new MV.List,Type:"Simple",IsInWork:!1,DataType:"XML",RenderAll:!0,constructor:function(a){this.id=a},init:function(a){this.IsInit=!0;var b=null;if("undefined"==typeof a){var c=mv_loadAttrTableFile(this.id,!0);if(null==c)return;this.Event=c.getNode("cluster").getAttribute("event");for(var d=mv_getXMLSubNodes(c.getNode("cluster")),
e=0;e<d.length;e++)"cluster"==d[e].nodeName&&(this.Type="ClustImages"),this.Symbols.push(this.makeSymbol(d[e]));this.RenderAll&&(b=c.Headings,a=mv_XMLFileArray[this.id].getRecords())}this.RenderAll&&this.makeClusterRecords(a,b)},makeSymbol:function(a){var b=new MV.XMLSymbol(a);b.min=mv_getXMLAttrValue(a,"min",0);b.max=mv_getXMLAttrValue(a,"max",0);b.event=mv_getXMLAttrValue(a,"event","");return b},clearClusters:function(){this.Clusters.deleteMe();mv_removeSVGele(this.id+"CLLayer")},makeClusterRecords:function(a,
b){for(var c=0;c<a.length;c++)this.addClusterRecord(a[c],b)},addClusterRecord:function(a,b,c){var d=null;switch(this.DataType){case "XML":d=new MV.XMLClusterRecord(a,b);break;case "XML2":d=new MV.XMLClusterRecord2(a,b,c);break;case "DBPictures":d=new MV.PictureClusterRecord(a)}this.ClusterRecords.addMe(d)},toggleVisibilityRec:function(a,b){var c=this.ClusterRecords.item(a);this.toggleVisibility(c,b)},toggleVisibilityShortList:function(a){for(var b=0;b<this.ClusterRecords.length();b++){var c=this.ClusterRecords.item(b);
c.Visible=!1;for(var d=0;d<a.length;d++)if(a[d]==c.id){c.Visible=!0;a.splice(d,1);break}}this.fillClusters()},toggleVisibilityList:function(a,b){for(var c=0;c<this.ClusterRecords.length();c++){var d=this.ClusterRecords.item(c);d.Value==a&&this.toggleVisibility(d,b)}this.fillClusters()},toggleVisibility:function(a,b){a.Visible=b;if(null!=a.AttachedLayer){var c=mv_Map.Layers.item(a.AttachedLayer);mv_changeLayerVis2(!b,c)}},fillClusters:function(){if(1!=this.IsInWork&&(this.IsInWork=!0,this.HasMoreInOne=
mv_Map.Pressed=!1,this.clearClusters(),null==mv_Map.Root.getElementById(this.id+"CLLayer"))){var a=this.GridSize*mv_Map.CurrentVB.Width/mv_Map.CurrentExt.Width;mv_Doc.Para=Array(this);var b=this.ClusterRecords.length();1E3<b&&(b=1E3);mv_fillCluster(0,b,1E3,a)}},addMarker:function(a,b){if(null!=a.Location&&0!=a.Visible){var c=a.Location;if(0!=mv_Map.CurrentVB.pointWithIn(c)){for(var d=0,e=this.Clusters.length();d<e;d++){var f=this.Clusters.item(d);if(f.VB.centerP().distance(c,!1)<=b){f.addMarker(a,
c);this.HasMoreInOne=!0;return}}this.addCluster(a,c)}}},addCluster:function(a,b){var c=new MV.Viewbox(b),c=new MV.MarkerCluster({id:this.id+"cl"+this.Clusters.length(),Type:this.Type,FirstRec:a,VB:c,Headings:this.Headings,XMLAccess:this.XMLAccess},b);this.Clusters.addMe(c)},draw:function(){for(var a=mv_makeSVGNode(mv_Map.Root,"g",{id:this.id+"CLLayer"}),b=0,c=this.Clusters.length();b<c;b++){var d=this.Clusters.item(b);d.draw(a,this.getSymbol(d.RecIds.length),this.Event)}mv_Map.Root.getElementById(this.id).appendChild(a);
mv_Map.MaxScaleFakt==mv_Map.Scale&&1==this.HasMoreInOne&&(mv_Map.MaxScaleFakt=2*mv_Map.Scale)},getSymbol:function(a){for(var b=0;b<this.Symbols.length;b++)if(a>=parseFloat(this.Symbols[b].min)&&a<=parseFloat(this.Symbols[b].max))return this.Symbols[b];return this.Symbols[0]}});dojo.declare("MV.MarkerCluster",null,{Symbol:null,PDisplF:"",constructor:function(a,b){dojo.mixin(this,a);this.RecIds=[];this.Symbols={};"Pictures"==this.Type&&(this.Titles=[],this.Images=[]);this.addMarker(this.FirstRec,b)},
addMarker:function(a,b){var c=new MV.Viewbox(b);this.VB.union(c);this.RecIds.push(a.id);switch(this.Type){case "ClustImages":c=a.Symbol;try{this.Symbols[c.src]=c}catch(d){}break;case "Pictures":this.Images.push(mv_Doc.BaseURL+a.Src),this.Titles.push(a.Txt)}},draw:function(a,b,c){var d=this.VB.centerP(),e=this.id;1==this.RecIds.length&&(e=this.RecIds[0],"none"==c&&(e+="none"),this.Symbol=this.FirstRec.Symbol,"ClustImages"==this.Type&&(this.Type="ClustImagesSingle"));"Pictures"==this.Type&&(this.Symbol=
this.FirstRec.Symbol);("Simple"==this.Type||"ClustImages"==this.Type)&&1<this.RecIds.length&&(this.Symbol=b);b=mv_Map.CurrentVB.Width/mv_Map.CurrentExt.Width;switch(this.Type){case "ClustImages":c=null;var e=mv_makeSVGNode(mv_Map.Root,"g",{id:e,transform:"translate(0,0)"}),f=0,g;for(g in this.Symbols)f++;var f=Math.ceil(Math.sqrt(f)),h=mv_makeSVGNode(mv_Map.Root,"rect",{fill:mv_Doc.BGColor2,"fill-opacity":.3,stroke:"dimgray","stroke-width":1*mv_Map.LegMapKoeff/mv_Map.Scale,"pointer-events":"all"});
e.appendChild(h);var k=1*b,q=k,r=k,n=0,l=0,t=0,p=0;for(g in this.Symbols){var m=this.Symbols[g];c=this.drawSymbol(m,q,r,b);e.appendChild(c);q=q+b*m.width+k;n++;t=Math.max(t,b*m.height+k);n==f&&(l=Math.max(l,q),q=k,r=r+b*m.height+k,n=0,p+=t,t=0)}g=d.x-l/2+b*m.width/2;p+=t;e.setAttributeNS(null,"transform","translate("+g+","+(d.y-p/2+b*m.height/2)+")");1<this.RecIds.length&&(p+=b*m.height*.25,l+=b*m.width*.25,q=b*m.width*-.625,r=b*m.height*-.625,mv_setAttrSVG(h,{x:q,y:r,width:l,height:p}),mv_setAttrSVG(h,
{onmouseover:"parent.mv_mapTipOver(evt,'"+this.RecIds.length+" "+mv_Doc.getText("Records","records")+"');"}));a.appendChild(e);break;case "Pictures":c=this.drawSymbol(this.Symbol,d.x,d.y,b);c.setAttributeNS(null,"id",e);a.appendChild(c);mv_setAttrSVG(c,{onmouseup:"parent.mv_Map.Pressed = false;parent.mv_lightBox('"+this.Images.join("#")+"|"+this.Titles.join("#")+"')"});1==this.RecIds.length?mv_setAttrSVG(c,{onmouseover:"parent.mv_mapTipOver(evt,'"+this.Titles[0]+"');"}):mv_setAttrSVG(c,{onmouseover:"parent.mv_mapTipOver(evt,'"+
this.RecIds.length+" "+mv_Doc.getText("Pictures","pictures")+"');"});break;default:c=this.drawSymbol(this.Symbol,d.x,d.y,b),c.setAttributeNS(null,"id",e),1==this.RecIds.length&&(m="parent.mv_mapTipOver(evt,"+this.FirstRec.Txt+");",null!=this.FirstRec.AttachedRec&&(m=m+" parent.mv_hiliteAttachedRec('"+this.FirstRec.AttachedRec+"');"),mv_setAttrSVG(c,{onmouseover:m})),a.appendChild(c),1<this.RecIds.length&&"Simple"==this.Type&&(r=d.y+5*b,c=mv_makeSVGNode(mv_Map.Root,"text",{x:d.x,y:r,"text-anchor":"middle",
"font-size":13*b,"pointer-events":"none"},this.RecIds.length),a.appendChild(c))}},drawSymbol:function(a,b,c,d){switch(a.shape){case "img":var e=a.makeSVGNode(mv_Map.Root,mv_Map.LegMapKoeff/mv_Map.Scale,{x:b-d*a.width/2,y:c-d*a.height/2});break;case "circle":e=a.makeSVGNode(mv_Map.Root,mv_Map.LegMapKoeff/mv_Map.Scale,{cx:b,cy:c})}return e}});dojo.declare("MV.XMLClusterRecord2",null,{Location:null,Symbol:null,Txt:"",Value:"",Visible:!0,AttachedLayer:null,AttachedRec:null,constructor:function(a,b,c){this.id=
a.getAttribute("id");this.Txt=b.setName(a);this.Txt=mv_quoteSQLString(!0,dojo.trim(this.Txt));this.Value=c.Value;this.Visible=c.Visible;this.AttachedLayer=c.AttachedLayer;null!=this.AttachedLayer&&(this.AttachedRec=this.AttachedLayer+this.id.substring(this.id.indexOf("rec")));b=mv_getXMLNodeValue(a,"lon",null);a=mv_getXMLNodeValue(a,"lat",null);null!=b&&null!=a&&(b=mv_Map.getMapviewX(parseFloat(b)),a=mv_Map.getMapviewY(parseFloat(a)),this.Location=new MV.Point(b,a),this.Symbol=new MV.Symbol({shape:"img",
src:c.icon,width:26,height:26}))}});dojo.declare("MV.XMLClusterRecord",null,{Visible:!0,constructor:function(a,b){this.id=a.getAttribute("id");this.Txt=b.setName(a);this.Txt=mv_quoteSQLString(!0,dojo.trim(this.Txt));this.Location=new MV.Point(a);var c=mv_getXMLSubNode(a.selectSingleNode("sym").firstChild);this.Symbol=new MV.XMLSymbol(c)}});dojo.declare("MV.PictureClusterRecord",null,{ImgFakt:60,Visible:!0,constructor:function(a){a=a.split("|");this.id=a[0];var b=parseInt(a[1]),c=parseInt(a[2]);b>
c?(c=this.ImgFakt*c/b,b=this.ImgFakt):(b=this.ImgFakt*b/c,c=this.ImgFakt);var d=mv_Map.getMapviewY(parseFloat(a[3])),e=mv_Map.getMapviewX(parseFloat(a[4]));this.Location=new MV.Point(e,d);this.Src=a[5];this.Txt=dojo.trim(a[6]);this.Symbol=new MV.Symbol({shape:"img",src:this.Src,width:b,height:c})}})}
function mv_fillCluster(a,b,c,d){for(;a<b;a++){var e=mv_Doc.Para[0].ClusterRecords.item(a);mv_Doc.Para[0].addMarker(e,d)}b==mv_Doc.Para[0].ClusterRecords.length()?(mv_Doc.Para[0].draw(),mv_Doc.Para[0].IsInWork=!1):(a=b,b=a+c,b>mv_Doc.Para[0].ClusterRecords.length()&&(b=mv_Doc.Para[0].ClusterRecords.length()),mv_fillClusterTimeout(a,b,c,d))}function mv_fillClusterTimeout(a,b,c,d){window.setTimeout("mv_fillCluster("+a+","+b+","+c+","+d+")",0)}
function mv_cluster(a){mv_Map.Pressed=!1;if(null!=mv_Map.MapPoint){var b=mv_Map.getMapPoint(a.clientX,a.clientY);if(mv_Map.MapPoint.x!=b.x&&mv_Map.MapPoint.y!=b.y)return;mv_Map.MapPoint=null}b=mv_getRecEle(a);b=mv_getRecId(b);if(-1==b.indexOf("none")&&(-1!=b.indexOf("rec")&&mv_identify(a,"list"),-1!=b.indexOf("cl")))switch(a=b.substring(0,b.indexOf("cl")),a=mv_Map.Layers.item(a).LayerObj.Clusters.item(b),a.Symbol.event){case "zoom":0==mv_zoomCluster(a)&&mv_identifyCluster(a);break;case "identify":mv_identifyCluster(a);
break;case "zoom+identify":mv_zoomCluster(a),mv_identifyCluster(a)}}function mv_zoomCluster(a){a=a.VB;if(a.X==a.XMax()&&a.Y==a.YMin())return!1;mv_zoomToExtent(a.X,a.XMax(),a.Y,a.YMin(),20);return!0}function mv_identifyCluster(a){mv_closeTPs(mv_Map.Identifys);for(var b=0;b<a.RecIds.length;b++)mv_identify(a.RecIds[b],"list")}function mv_getClusterLayer(a){null==a.LayerObj&&(a.LayerObj=new MV.MarkerClusters(a.id));0==a.LayerObj.IsInit&&a.LayerObj.init();a.LayerObj.fillClusters()}
function mv_hiliteAttachedRec(a){if(!mv_blnInit)return!0;ele=mv_Map.Root.getElementById(a);var b=mv_getThemaIdFromRecId(a),b=mv_Map.Layers.item(b),c=ele.getAttributeNS(mv_Doc.ProgNS,"recIds");a=mv_getRecIdsFromParaList(a,c);mv_HighlightColors&&mv_HighlightColors.deleteMe();mv_HighlightColors=new MV.ColorList({recIds:a,prop:b.SVGLayerProp.StyleProp,doLoop:!1,doColor:!0})}var mv_MagnifyElements=null;
function mv_declareClassChart(){dojo.declare("MV.Chart",null,{Type:"",Grid:null,MapHighlight:!1,Plots:null,Axes:null,Chart:null,ChartBig:null,DoSort:!1,Title:"",TitleBig:"",DoEnlarge:!1,Legend:!1,LegExtent:mv_Doc.LegLayout.LegKastOffset,LegendEntries:0,constructor:function(a,b){this.Plots=[];this.Axes=new MV.List;this.id=a;var c=b.getChartInfo("fill",mv_Doc.TableColor,!1),d=b.getChartInfo("stroke","#666",!1);this.Legend=b.getChartInfo("legend",!1,!1);this.maxWidth=b.getChartInfo("maxWidth","0px",
!0);this.DoEnlarge=b.getChartInfo("enlarged",this.DoEnlarge,!1);this.thChart=Object({fill:c,stroke:{width:2,color:d}});this.thPlotarea=Object({fill:c});this.thAxis=Object({majorTick:{color:"#aaa",width:.5,length:4},stroke:{color:"#666",width:1},tick:{position:"center",font:this.getFont(7),fontColor:"#333"},minorTick:{color:"#aaa",width:.5,length:4}});this.thSeries=Object({stroke:{width:1,color:"#666"},outline:null,font:this.getFont(8),fontColor:"#000"});this.thMarkers={CIRCLE:"m-3,0 c0,-4 6,-4 6,0 m-6,0 c0,4 6,4 6,0",
SQUARE:"m-3,-3 l0,6 6,0 0,-6 z",DIAMOND:"m0,-3 l3,3 -3,3 -3,-3 z",CROSS:"m0,-3 l0,6 m-3,-3 l6,0",X:"m-3,-3 l6,6 m0,-6 l-6,6",TRIANGLE:"m-3,3 l3,-6 3,6 z",TRIANGLE_INVERTED:"m-3,-3 l3,6 3,-6 z",BIGCIRCLE:"m-6,0 c0,-8 12,-8 12,0, m-12,0 c0,8 12,8 12,0",BIGSPIRAL:"m-12,0 c 0,6 12,6 12,0, m0,0 c 0,-6 12,-6 12,0, m-12,-12, c -6,0 -6,12 0,12, m0,0 c 6,0 6,12 0,12",BIGBIGSPIRAL:"m-24,0 c 0,12 24,12 24,0, m0,0 c 0,-12 24,-12 24,0, m-24,-24, c -12,0 -12,24 0,24, m0,0 c 12,0 12,24 0,24",BIGSTAR:"m-6,-6 6,3 6,-3 -3,6 3,6 -6,-3 -6,3 3,-6 -3,-6z",
BIGBIGSTAR:"m-12,-12 12,6 12,-6 -6,12 6,12 -12,-6 -12,6 6,-12 -6,-12z",BIGSQUARE:"m-6,-6 12,0 0,12 -12,0z"};this.thSeriesThemes=this.makeColPalette();this.theme=this.makeTheme();d=b.Node.selectNodes("axis");for(c=0;c<d.length;c++){var e=d[c],e=new MV.ChartAxis(e.getAttribute("name"),c,e.selectSingleNode("valueAxis"),e.selectSingleNode("labelAxis"));this.Axes.addMe(e)}this.seriesNames=[];d=b.Node.selectNodes("plot");for(c=0;c<d.length;c++){var f=d[c];this.Type=b.getNodeValue("type","Columns",f);var e=
this.Axes.item(b.getNodeValue("axis","",f)),g=new MV.ChartPlot("plot"+c,this.Type,e,this.theme);"Pie"==g.Type&&null!=g.Axis&&this.Axes.deleteItem(g.Axis.id);try{dojo.forEach(f.attributes,function(a){g.Plot[a.nodeName]=mv_str2bool(a.nodeValue)})}catch(k){}g.Tooltip=b.getNodeValue("tooltip",null,f);try{g.Click=b.getNodeValue("click",null,f).replace(/#/g,"")}catch(k){g.Click=null}e=f.selectNodes("series");for(f=0;f<e.length;f++){var h=this.makeSeries(e[f],g,c,f);g.Series.addMe(h)}this.Plots.push(g)}1==
b.getChartInfo("grid",!0,!1)&&this.makeGrid(b.Node.selectSingleNode("grid"));this.Title=b.getChartInfo("title",this.Title,!1);this.TitleBig=b.getChartInfo("title",this.Title,!0);if(dojo.isIE||dojo.isOpera)this.Title=mv_replaceBR(this.Title),this.TitleBig=mv_replaceBR(this.TitleBig);try{b.Node.selectSingleNode("sort").hasChildNodes()&&(this.DoSort=!0)}catch(k){}},makeSeries:function(a,b,c,d){var e=mv_cloneObj(b.Args),f=a.selectSingleNode("fields").firstChild.nodeValue;if(-1!=f.indexOf("-"))for(var g=
Number(f.substring(f.indexOf("f")+1,f.indexOf("-"))),h=Number(f.substring(f.lastIndexOf("f")+1)),f=[];g<=h;g++)f.push("f"+String(g));else f=a.selectSingleNode("fields").firstChild.nodeValue.split(",");var k=!1;try{dojo.forEach(a.selectSingleNode("sym").attributes,function(a){"fill"==[a.nodeName]||"stroke"==[a.nodeName]?("none"==a.nodeValue?0<=b.Type.toLowerCase().indexOf("areas")?e[a.nodeName]=chartCol:e[a.nodeName]=[0,0,0,0]:e[a.nodeName]=mv_makeColor(a.nodeValue),"stroke"==[a.nodeName]&&(k=!0)):
e[a.nodeName]=mv_str2bool(a.nodeValue)})}catch(q){}k&&(h=e.width,"undefined"==typeof h&&(h=1),e.stroke={color:e.stroke,width:h},null!=e.style&&(e.stroke.style=e.style));null!=e.marker&&(e.marker=this.theme.markers[e.marker]);c=mv_getXMLAttrValue(a,"name","series"+String(c)+"_"+String(d));c=this.getSeriesUniqueName(c);this.seriesNames.push(c);a=mv_getXMLAttrValue(a,"title",null);f=new MV.ChartSeries({id:c,Fields:f,Args:e,Title:a});e=null;return f},getSeriesUniqueName:function(a){require(["dojo/_base/array"],
function(b){-1<b.indexOf(this.seriesNames,a)&&(a=a+"_"+String(this.getSeriesCount()))});return a},getSeriesCount:function(){for(var a=0,b=0;b<this.Plots.length;b++)a+=this.Plots[b].Series.length();return a},getTitle:function(a){return a?this.TitleBig:this.Title},getGrid:function(a){return a?this.GridBig:this.Grid},makeGrid:function(a){if(0!=this.Axes.length()){var b=Object({type:"Grid",hAxis:this.Axes.item(0).LabAxisName,vAxis:this.Axes.item(0).ValAxisName,hMajorLines:!0,hMinorLines:!0,vMajorLines:!1,
vMinorLines:!1});try{dojo.forEach(a.attributes,function(a){b[a.nodeName]=mv_str2bool(a.nodeValue)})}catch(e){}if("Bars"==this.Type){var c=b.hMajorLines,d=b.hMinorLines;b.hMajorLines=b.vMajorLines;b.vMajorLines=c;b.hMinorLines=b.vMinorLines;b.vMinorLines=d}this.Grid=b;b=mv_cloneObj(b);try{dojo.forEach(a.selectSingleNode("enlarged").attributes,function(a){b[a.nodeName]=mv_str2bool(a.nodeValue)})}catch(e){}this.GridBig=b}},makeColSeries:function(a){var b=[];dojo.forEach(a,function(a){b.push({fill:a})});
return b},makeColPalette:function(){var a=dojox.color.Palette.generate(mv_Doc.BGColor2,"analogous").colors;return this.makeColSeries(a)},makeTheme:function(){return new dojox.charting.Theme({markers:this.thMarkers,chart:this.thChart,plotarea:this.thPlotarea,axis:this.thAxis,series:this.thSeries,seriesThemes:this.thSeriesThemes})},makeChart:function(a,b){var c=0==b?this.Chart=new dojox.charting.Chart2D(a):this.ChartBig=new dojox.charting.Chart2D(a);c.id=this.id;c.theme=this.theme;""!=this.getTitle(b)&&
(c.title=this.getTitle(b),c.titleFont=this.getFont(11));var d=!1,e=this.getGrid(b);null!=e&&"undefined"!=typeof e.inFront&&1==e.inFront&&(c.addPlot("Grid",e),d=!0);for(var f=0;f<this.Axes.length();f++){var g=this.Axes.item(f);null!=g.getValAxis(b)&&c.addAxis(g.ValAxisName,g.getValAxis(b));null!=g.getLabAxis(b)&&c.addAxis(g.LabAxisName,g.getLabAxis(b))}for(f=0;f<this.Plots.length;f++){g=this.Plots[f];c.addPlot(g.Name,g.Plot);switch(g.Type){case "Candlesticks":var h=g.Series.item(0);this.addSeries(c,
h.Title,h.Series,h.Args);break;case "Scatter":h=g.Series.item(0);this.addSeries(c,h.Title,h.Series,h.Args);break;default:for(var k=0,q=g.Series.length();k<q;k++)h=g.Series.item(k),this.addSeries(c,h.id,h.Series,h.Args)}new dojox.charting.action2d.Tooltip(c,g.Name);null!=g.Plot.highlight&&1!=g.Plot.highlight||new dojox.charting.action2d.Highlight(c,g.Name,{highlight:mv_Doc.HiColor});null!=g.Plot.hiliteMatchRecords&&1==g.Plot.hiliteMatchRecords&&c.connectToPlot(g.Name,mv_hiliteMatchRecords);null!=g.Plot.magnifyScale&&
new dojox.charting.action2d.Magnify(c,g.Name,{scale:Number(g.Plot.magnifyScale)});"Pie"==this.Type&&new dojox.charting.action2d.MoveSlice(c,g.Name);this.MapHighlight&&c.connectToPlot(g.Name,mv_hiliteMapFromGraph);null!=g.Click&&c.connectToPlot(g.Name,mv_clickDatagraphFeatures)}null!=e&&0==d&&c.addPlot("Grid",e);c.render()},makeLegend:function(a,b){var c=0==b?this.Chart:this.ChartBig;if(0!=this.LegendEntries){var d=0,c=c.series||c.chart.series;if("Scatter"==this.Type)for(c=0;c<this.Plots.length;c++)for(var e=
this.Plots[c].Series,f=0;f<e.length();f++){var g=e.item(f);if(null!=g.LegendEntries)for(var h in g.LegendEntries)this.addLegendEntry(a,g.LegendEntries[h],h,d),d+=this.LegExtent}else if("dojox.charting.plot2d.Pie"==c[0].chart.stack[0].declaredClass){var k=c[0].chart.stack[0];"number"!=typeof k.run.data[0]&&dojo.forEach(k.run.data,function(b,c){this.addLegendEntry(a,k.dyn[c],b.legend||b.text||b.y,d);d+=this.LegExtent},this)}else dojo.forEach(c,function(b){-1==b.name.indexOf("dummy")&&(this.addLegendEntry(a,
b.dyn,b.legend||b.name,d),d+=this.LegExtent)},this)}},addLegendEntry:function(a,b,c,d){var e=this.LegExtent,f=2*this.LegExtent;if(b.fill)a.createRect({x:2,y:d+2,width:f-4,height:e-4}).setFill(b.fill).setStroke(b.stroke);else if(b.stroke||b.marker){var g={x1:2,y1:e/2+d,x2:f,y2:e/2+d};b.stroke&&a.createLine(g).setStroke(b.stroke);b.marker&&a.createPath({path:"M"+f/2+" "+(e/2+d)+" "+b.marker}).setFill(b.markerFill).setStroke(b.markerStroke)}a.createText({x:f+5,y:d+12,text:c}).setFont({family:"Arial",
size:"8pt"}).setFill("black")},getFont:function(a){return"normal normal normal "+a+"pt Tahoma"},addSeries:function(a,b,c,d){a.addSeries(b,c,d)},getSeriesType:function(a){if(1==this.DoSort)return!0;a=this.Plots[a];return"Areas"!=a.Type&&"Lines"!=a.Type&&"StackedAreas"!=a.Type||0!=a.Plot.markers?!0:!1},canRecCol:function(){for(var a=0;a<this.Plots.length;a++)if(this.Plots[a].CanRecCol)return!0;return!1}});dojo.declare("MV.ChartPlot",null,{Plot:null,Map2ChartIndex:0,XValues:!1,Name:"",Series:null,Type:"",
CanRecCol:!1,Args:null,Axis:null,Tooltip:null,constructor:function(a,b,c,d){this.Args={};this.Name=a;this.Plot=Object({type:b});this.Type=b;null!=c&&(this.Axis=c,""!=c.LabAxisName&&(this.Plot.hAxis=c.LabAxisName),""!=c.ValAxisName&&(this.Plot.vAxis=c.ValAxisName),0<=b.indexOf("Bars")&&c.setToBars());this.Args.plot=a;this.Series=new MV.List;switch(b){case "Default":this.Plot.type="Areas";this.AreaLineTypeSett();this.setPlotMarkers(d);break;case "Lines":this.AreaLineTypeSett();break;case "Areas":this.AreaLineTypeSett();
this.Map2ChartIndex=2;break;case "Markers":this.AreaLineTypeSett();this.setPlotMarkers(d);break;case "MarkersOnly":this.setPlotMarkers(d);break;case "Stacked":this.AreaLineTypeSett();this.setPlotMarkers(d);break;case "StackedLines":this.AreaLineTypeSett();break;case "StackedAreas":this.AreaLineTypeSett();this.Map2ChartIndex=2;break;case "Bars":this.CanRecCol=!0;this.setColumnArgs();break;case "ClusteredBars":this.setColumnArgs();this.CanRecCol=!0;break;case "StackedBars":this.setColumnArgs();this.CanRecCol=
!0;break;case "ClusteredColumns":this.setColumnArgs();this.CanRecCol=!0;break;case "Columns":this.setColumnArgs();this.CanRecCol=!0;break;case "StackedColumns":this.setColumnArgs();this.CanRecCol=!0;break;case "Pie":this.CanRecCol=!0;break;case "Scatter":this.setPlotMarkers(d);break;case "Candlesticks":this.setColumnArgs();break;case "Spider":this.Plot=Object({type:b,labelOffset:-10,divisions:4,seriesFillAlpha:.2,markerSize:3,precision:0,spiderType:"ploygon",radius:115})}},AreaLineTypeSett:function(){this.Map2ChartIndex+=
1;this.Args.stroke={color:"#666",width:1}},setColumnArgs:function(){this.Plot.gap=2;this.Plot.minBarSize=5;this.Plot.maxBarSize=40},setPlotMarkers:function(a){this.XValues=this.CanRecCol=!0;this.Plot.markers=!0;this.Plot.marker=a.markers.CIRCLE;this.Plot.marker.stroke="red"},getSerieByName:function(a){return this.Series.item(a)},doLabels:function(a){return null==this.Axis?!1:this.Axis.doLabels(a)},isMultiColored:function(){return"Columns"==this.Type||"Bars"==this.Type||"Pie"==this.Type||"MarkersOnly"==
this.Type?!0:!1}});dojo.declare("MV.ChartSeries",null,{Fields:null,Series:null,Args:null,constructor:function(a){dojo.safeMixin(this,a);this.Series=[]}});dojo.declare("MV.ChartAxis",null,{ValAxis:null,LabAxis:null,ValAxisBig:null,LabAxisBig:null,ValAxisName:"",LabAxisName:"",LabField:null,constructor:function(a,b,c,d){this.id=a;var e=!1;if(dojo.isIE||dojo.isOpera)e=!0;if(null!=c){var f=Object({includeZero:!0,fixUpper:"minor",fixLower:"minor",vertical:!0,leftBottom:!0,min:0});1==b&&(f.leftBottom=!1);
f.titleFont=this.getFont(8);this.ValAxisName="val"+a;dojo.forEach(c.attributes,function(a){f[a.nodeName]=mv_str2bool(a.nodeValue)});"undefined"!=typeof f.title&&e&&(f.title=mv_replaceBR(f.title));this.ValAxis=f;f=mv_cloneObj(f);try{dojo.forEach(c.selectSingleNode("enlarged").attributes,function(a){f[a.nodeName]=mv_str2bool(a.nodeValue)})}catch(k){}"undefined"!=typeof f.title&&e&&(f.title=mv_replaceBR(f.title));this.ValAxisBig=f}if(null!=d)if(null==d.getAttribute("ref")){var g=Object({leftBottom:!0,
vertical:!1,htmlLabels:!0});0==b&&(g.titleOrientation="away");1==b&&(g.leftBottom=!1);g.titleGap=5;g.titleFont=this.getFont(8);this.LabAxisName="lab"+a;dojo.forEach(d.attributes,function(a){var b=a.nodeValue,b=mv_str2bool(b);0==isNaN(b)&&(b=Number(b));g[a.nodeName]=b});"undefined"!=typeof g.title&&e&&(g.title=mv_replaceBR(g.title));this.LabAxis=g;g=mv_cloneObj(g);try{dojo.forEach(d.selectSingleNode("enlarged").attributes,function(a){g[a.nodeName]=mv_str2bool(a.nodeValue)})}catch(k){}"undefined"!=
typeof g.title&&e&&(g.title=mv_replaceBR(g.title));this.LabAxisBig=g;a=d.selectNodes("label");if(0<a.length){b=[];for(c=0;c<a.length;c++){var h={};h.value=c+1;h.text=a[c].firstChild.nodeValue;e&&(h.text=mv_replaceBR(h.text));b.push(h)}this.setLabels(b)}try{this.LabField=d.selectSingleNode("labelField").firstChild.nodeValue}catch(k){}}else this.LabAxisName="lab"+d.getAttribute("ref")},getValAxis:function(a){return a?this.ValAxisBig:this.ValAxis},getLabAxis:function(a){return a?this.LabAxisBig:this.LabAxis},
setToBars:function(){null!=this.ValAxis&&(this.ValAxis.titleOrientation="away");this.ValAxis.vertical=!1;this.ValAxisBig.vertical=!1;null!=this.LabAxis&&(this.LabAxis.vertical=!0,this.LabAxisBig.vertical=!0)},setLabels:function(a){null!=a&&0!=a.length&&null!=this.LabAxis&&(this.LabAxis.labels=a,this.LabAxisBig.labels=a)},getFont:function(a){return"normal normal normal "+a+"pt Tahoma"},doLabels:function(a){if(0==a){if(null==this.LabAxis||null!=this.LabAxis.labels)return!1}else if(null==this.LabAxisBig||
null!=this.LabAxisBig.labels)return!1;return!0}})}function mv_makeColor(a){if(-1<a.indexOf("[")&&-1<a.indexOf("]")){a=a.replace("[","");a=a.replace("]","");a=a.split(",");for(var b=0;b<a.length;b++)a[b]=Number(a[b]);return a}if(-1<a.indexOf(",")){a=a.split(",");for(var c=[],b=0;b<a.length;b++)c.push({fill:a[b]});return c}return a}function mv_replaceBR(a){try{a=a.replace(/<br\/>/g,""),a=a.replace(/<br>/g,"")}catch(b){}return a}
function mv_declareClassDatagraphTP(){mv_Doc.Datagraphs=new MV.List;dojo.declare("MV.DatagraphTP",[dijit.TitlePane],{id:"",dataObj:null,constructor:function(a){dojo.mixin(this,a);mv_Doc.Datagraphs.addMe(this)},deleteItem:function(){dijit.byId("legch"+this.id)&&dijit.byId("legch"+this.id).destroy();this.destroy();mv_Doc.Datagraphs.deleteItem(this.id)}});dojo.declare("MV.MagnifyList",MV.List,{RecArray:null,constructor:function(a){dojo.safeMixin(this,a);this.RecArray=[];for(a=0;a<this.recIds.length;a++)this.fillRecArray(this.recIds[a],
0)},fillRecArray:function(a,b){var c=mv_Map.Root.getElementById(a);this.RecArray.push(c);this.insertEle(c)},insertEle:function(a,b,c,d){b=a.getAttributeNS(null,"r");a=new MV.Magnify(a,"r",b);this.addMe(a)},deleteMe:function(){for(;0<this.List.length;)this.List.pop().deleteMe();this.inherited(arguments)},killMe:function(){for(;0<this.List.length;)this.List.pop().killMe();this.inherited(arguments)}});dojo.declare("MV.Magnify",null,{constructor:function(a,b,c){this.ele=a;this.Prop=b;this.Value=c;this.setValue(3*
c)},setValue:function(a){this.ele.setAttributeNS(null,this.Prop,a)},deleteMe:function(){this.ele.setAttributeNS(null,this.Prop,this.Value)}})}function mv_deleteGraphTP(a){a=dijit.byId(a);null!=a&&a.deleteItem()}
function mv_swapDatagraph(a){var b=dijit.byId("MVlistGraphObject");if(null!=b){var c=[];a?c.push(a):require(["dojo/query","dijit/registry"],function(a,b){a("#MVlegendContent [id^='MVsharedSel']").forEach(function(a){a=b.byNode(a);c.push(a.value)})});var d="";c.forEach(function(a){_mv_layerOrParentIsTurnedOn(a,!0)&&(d=mv_colorMapAnalyzeStr(a,"themaId").split(",").shift()+",g0")});""!=d&&b.get("value")!=d&&b.set("value",d)}}
function mv_makeDatagraph(a){if(0!=a.length){var b=!1;dojo.byId("MVborderTabContainer")&&(b=!0);var c=a.split(",");a=c.shift();c=c.shift();if(dijit.byId(a+c))if(1==b)mv_deleteTP(a+c);else return b=dijit.byId(a+c),mv_closeTPs(mv_Doc.Datagraphs),b.toggle(),!0;var d=mv_loadAttrTableFile(a,!0);if(null!=d&&null!=d.Graphs){var e=d.getRecords();if(null!=e&&0!=e.length){var f=new MV.XMLChart(d.Graphs.selectSingleNode("graph[@id = '"+c+"']"));if(null!=f){var g=dojo.byId("MVgraphContent");mv_makeDatagraphTP(a,
c,f,e,d,g,b)}}}}}
function mv_makeDatagraphTP(a,b,c,d,e,f,g){if(1==g)for(;f.firstChild;)f.removeChild(f.firstChild);var h=mv_makeNode(document,"div",{});h.innerHTML="";var k=a+b;0==g&&(func="mv_deleteGraphTP('"+k+"');",mv_makeButton(h,document,mv_Doc.getText("Close","Clear Selection"),"fa fa-times MVfa-but",func));var q=mv_getXMLAttrValue(c.Node,"title","");""!=c.getNodeValue("desc","")&&(func="mv_datagraphInfo('"+a+"','"+b+"');",mv_makeButton(h,document,mv_Doc.getText("Graph","Plot Information"),"fa fa-question MVfa-but",
func));b=new MV.DatagraphTP({id:k,themaId:a,title:q});g?f.appendChild(h):(b.setContent(h),f.appendChild(b.domNode),b.startup(),mv_closeTPs(mv_Doc.Datagraphs),b.toggle());f=mv_makeNode(document,"div",{style:"cursor:all-scroll"});dojo.connect(f,"onclick",function(){GB_showPage(q,mv_Doc.BaseURL+"embfiles/chart.html?"+k)});h.appendChild(f);a=mv_makeDatagraphChart(a,k,c,d,e,f);a.Legend&&(c=mv_makeNode(document,"div",{id:k+"Legend"}),h.appendChild(c),h=mv_writeLegendGFXContainer(document,c,a.LegendEntries),
a.makeLegend(h,!1));b.data=a;g&&(g=dojo.byId("MVgraphContainer").offsetHeight-120,a.Chart.resize({w:"auto",h:g}))}function mv_datagraphInfo(a,b){var c=mv_XMLFileArray[a];if(null!=c){var d=new MV.XMLChart(c.Graphs.selectSingleNode("graph[@id = '"+b+"']")),c=d.getNodeValue("desc",""),d=mv_getXMLAttrValue(d.Node,"title","");mv_showInfo(d,c)}}
function mv_makeDatagraphChart(a,b,c,d,e,f){b=new MV.Chart(b,c);null!=mv_Map.Layers.item(a)&&(b.MapHighlight=!0);for(var g=b.DoSort,h=0;h<b.Plots.length;h++){var k=b.Plots[h],q=b.getSeriesType(h),r=k.Series;switch(k.Type){case "Scatter":for(var q=[],n=[],l=0,t=d.length;l<t;l++){var p=d[l],m={},v=k.Series.item("x");try{var z=p.selectSingleNode("c/"+v.Fields[0]).firstChild.nodeValue}catch(D){continue}m.x=z;v=k.Series.item("y");try{z=p.selectSingleNode("c/"+v.Fields[0]).firstChild.nodeValue}catch(D){continue}m.y=
z;mv_chartAddSym(m,p,b);b.MapHighlight&&mv_chartAddMapHighlight(m,p,a);var u=e.getNodeValue(p,"c/"+k.Axis.LabField,"");""!=u&&(q[u]=m);null!=k.Tooltip?mv_chartTooltip(k,p,m):(m.tooltip=m.x+" : "+m.y,""!=u&&(m.tooltip+=": "+u));null!=k.Click&&"identify"!=k.Click&&(m.url=e.getNodeValue(p,"c/"+k.Click,""));n.push(m)}r.item(0).Series=n;r.item(0).LegendEntries=q;b.LegendEntries=0;for(var A in q)b.LegendEntries+=1;break;default:var B=!1,C=null;k.doLabels(!1)&&(C=[],B=!0);for(var w=0;w<r.length();w++){var v=
r.item(w),n=[],G=v.Fields[0];b.LegendEntries+=1;l=0;for(t=d.length;l<t;l++){p=d[l];u=e.getNodeValue(p,"c/"+k.Axis.LabField,"");m={};try{var E=p.selectSingleNode("c/"+G).firstChild.nodeValue}catch(D){continue}switch(b.Type){default:if(B&&0==g&&0==w){var F=Object({value:l+1,text:u});C.push(F)}if(0==q)m=Number(E);else{m.y=Number(E);1==k.XValues&&0==g&&(m.x=l+1);m.txt=u;m.sort=l;if(null!=k.Tooltip)mv_chartTooltip(k,p,m);else{if(1<r.length)try{u+=", "+e.Headings.getHeadingByNodeName(G).Alias}catch(D){}""!=
u&&(u+=": ");m.tooltip=u+E}k.CanRecCol&&mv_chartAddSym(m,p,b)}}b.MapHighlight&&mv_chartAddMapHighlight(m,p,a);n.push(m)}v.Series=n}if(g){v=k.Series.item(0);switch(c.getNodeValue("sort","byValue")){case "byValue":0==q?v.Series.sort(mv_numsort2):v.Series.sort(mv_chartSortByNumber);break;case "byLabel":mv_chartSortByString(v.Series,"txt",d.length)}for(l=0;l<v.Series.length;l++)if(F=Object({value:l+1,text:v.Series[l].txt}),B&&C.push(F),k.XValues)for(v.Series[l].x=l+1,w=1;w<k.Series.length();w++)k.Series.item(w).Series[v.Series[l].sort].x=
l+1}B&&k.Axis.setLabels(C)}}b.makeChart(f,!1);return b}
function mv_chartTooltip(a,b,c,d,e){var f=a.Tooltip;a=a.Tooltip;for(var g;0<=f.indexOf("##");){var h=f.substring(f.indexOf("##")+2,f.indexOf("##",f.indexOf("##")+2));switch(h){case "label":a=a.replace("##label##",d);break;case "value":a=a.replace("##value##",e);break;default:if("undefined"!=typeof c[h])g="open"==[h]&&"undefined"!=typeof e?e:c[h];else try{g=b.selectSingleNode("c/"+h).firstChild.nodeValue,"url:"==g.substr(0,4).toLowerCase()&&(g=g.substr(4),g="<img src='"+mv_Doc.BaseURL+g+"'>")}catch(k){g=
""}a=a.replace("##"+h+"##",g)}f=f.substring(f.indexOf(h)+h.length+2)}c.tooltip=a}function mv_chartAddSym(a,b,c){try{dojo.forEach(b.selectSingleNode("sym").attributes,function(b){"marker"==[b.nodeName]?a.marker=c.theme.markers[b.nodeValue]:a[b.nodeName]=mv_str2bool(b.nodeValue)})}catch(d){}}function mv_chartAddMapHighlight(a,b,c){var d=b.getAttribute("id");a.recId=d;a.recIds=mv_getRecIdsFromXMLFile(b.selectSingleNode("ts"),d);a.themaId=c}function mv_chartSortByNumber(a,b){return a.y-b.y}
function mv_chartSortByString(a,b,c){for(var d=0;d<c-1;d++)for(var e=d+1;e<c;e++)if(a[e][b]<a[d][b]){var f=a[d];a[d]=a[e];a[e]=f}}
function mv_hiliteMatchRecords(a){if(null!=a.element){var b=a.run.data[a.index],c=b.themaId;switch(a.type){case "onmouseover":for(var d=0;d<mv_Doc.Datagraphs.length();d++){var e=mv_Doc.Datagraphs.item(d);if(e.themaId==c){for(var e=e.data,f=null,g=0,h=e.Chart.series[0].data.length;g<h;g++)if(e.Chart.series[0].data[g].recId==b.recId){f=e.Chart.series[0].group.children[g];e.selIndex=g;break}null!=f&&(f.originalFill||(f.originalFill=f.getShape()),g=e.thMarkers.BIGSTAR,e.id!=a.chart.id&&(g=e.thMarkers.BIGBIGSTAR),
x=f.bbox.l+(f.bbox.r-f.bbox.l)/2,y=f.bbox.t+(f.bbox.b-f.bbox.t)/2,f.setShape("M"+x+" "+y+g))}}break;case "onmouseout":for(d=0;d<mv_Doc.Datagraphs.length();d++)e=mv_Doc.Datagraphs.item(d).data,f=e.Chart.series[0].group.children[e.selIndex],null!=f&&f.setShape(f.originalFill)}}}
function mv_clickDatagraphFeatures(a){if(null!=a.element)switch(dojo.style(a.shape.getNode(),"cursor","pointer"),a.type){case "onclick":a=a.run.data[a.index],"undefined"==typeof a.url?mv_identify(a.recId,"list"):mv_showWindow(a.url,"",mv_Doc.TableWinSettings)}}
function mv_hiliteMapFromGraph(a){if(null!=a.element){var b=a.run.data[a.index],c=mv_Map.Layers.item(b.themaId);switch(a.type){case "onmouseover":if("undefined"==typeof b){if("spider_poly"!=a.element)return;b=a.chart.recIds[a.index]}mv_HighlightColors=new MV.ColorList({recIds:b.recIds,prop:c.SVGLayerProp.StyleProp,doLoop:!1,doColor:!0});break;case "onmouseout":mv_HighlightColors&&mv_HighlightColors.deleteMe(),mv_HighlightColors=null}if("circle"==c.SVGLayerProp.ScaleEle)switch(a.type){case "onmouseover":mv_MagnifyElements=
new MV.MagnifyList({recIds:b.recIds,prop:c.SVGLayerProp.StyleProp});break;case "onmouseout":mv_magnifyOut()}}}
function mv_hiliteGraphFromMap(a){a=mv_getRecEle(a);a=mv_getRecId(a);for(var b=mv_getThemaIdFromRecId(a),c=0;c<mv_Doc.Datagraphs.length();c++){var d=mv_Doc.Datagraphs.item(c);if(d.themaId==b){for(var e=d.data,d=null,f=0,g=e.Chart.series[0].data.length;f<g;f++)if(e.Chart.series[0].data[f].recId==a){d=e.Chart.series[0].group.children[f];e.selIndex=f;break}if(null!=d)switch(e.Type){case "Scatter":d.originalFill||(d.originalFill=d.getShape());e=e.thMarkers.BIGBIGSTAR;x=d.bbox.l+(d.bbox.r-d.bbox.l)/2;
y=d.bbox.t+(d.bbox.b-d.bbox.t)/2;d.setShape("M"+x+" "+y+e);break;case "Columns":d.originalFill||(d.originalFill=d.getFill()),d.setFill(mv_Doc.HiColor)}}}}
function mv_hiliteGraphFromMapOut(a){a=mv_getRecEle(a);a=mv_getRecId(a);a=mv_getThemaIdFromRecId(a);for(var b=0;b<mv_Doc.Datagraphs.length();b++){var c=mv_Doc.Datagraphs.item(b);if(c.themaId==a){var c=c.data,d=c.Chart.series[0].group.children[c.selIndex];if("undefined"!=typeof c.selIndex)switch(c.Type){case "Scatter":d.setShape(d.originalFill);break;case "Columns":d.setFill(d.originalFill)}}}}
function mv_magnifyOut(){if(!mv_blnInit)return!0;mv_MagnifyElements&&mv_MagnifyElements.deleteMe();mv_MagnifyElements=null}
function mv_enlargeGraph(a,b){var c=null,d=0;b=b.substr(1,b.length);if(0<=b.indexOf("rec")){url=b.split(";");var e=url[0],f=mv_getThemaIdFromRecId(e);try{c=mv_Map.Layers.item(f).IdentifyCharts[url[1]],d=1}catch(q){eval(url[1]);return}}else c=mv_Doc.Datagraphs.item(b).data;var g="undefined"==typeof window.innerHeight?document.documentElement.clientHeight:window.innerHeight,h="undefined"==typeof window.innerWidth?document.documentElement.clientWidth:window.innerWidth,h=h-70,g=g-120,f=a.getElementById("MVgraphContent");
if(c.Legend){var g=g-(c.LegendEntries*mv_Doc.LegLayout.LegKastOffset+10),k=dijit.byId("MVgraphLegend");"undefined"!=typeof k&&k.destroyRecursive();k=mv_writeLegendGFXContainer(a,a.getElementById("MVgraphLegend"),c.LegendEntries)}"0px"!=c.maxWidth&&(h=Math.min(Number(c.maxWidth.substring(0,c.maxWidth.indexOf("px"))),h));f.style.height=String(g)+"px";f.style.width=String(h)+"px";switch(d){case 0:c.ChartBig=null;c.MapHighlight=!1;break;case 1:d=mv_getDataObj(e,"chart"),mv_getChartValues(d,c,!0)}c.makeChart(f,
!0);c.Legend&&c.makeLegend(k,!0)}
function mv_makeIdentifyChartNode(a,b,c,d){if(null==c.data)return a;var e;1==d&&(e=mv_makeFullNode(b,"h2",{},c.getName()),a.appendChild(e));d=mv_Map.Layers.item(c.themaId).IdentifyCharts;if(null==d){d=[];e=mv_XMLFileArray[c.themaId].Identifies;if("MV.XMLChart"==e.declaredClass){var f=new MV.Chart(c.themaId,e);d.push(f)}else for(var g=0;g<e.length;g++)f=new MV.XMLChart(e[g]),f=new MV.Chart(c.themaId,f),d.push(f);mv_Map.Layers.item(c.themaId).IdentifyCharts=d}for(g=0;g<d.length;g++){f=d[g];mv_Map.Layers.item(c.themaId).XMLAccess?
mv_getChartValues(c,f,!1):mv_getChartValuesDB(c,f,!1);e=mv_makeNode(b,"p",{style:"margin-top:20px"});a.appendChild(e);e=mv_makeNode(b,"div",{id:"ch"+c.id+g,style:"cursor:all-scroll"});a.appendChild(e);var h=mv_Doc.BaseURL+"embfiles/chart.html?"+c.id+";"+g;dojo.connect(e,"onclick",function(){GB_showPage(c.getName(),h)});f.Chart=null;f.makeChart(e,!1);f.Legend&&(e=mv_makeNode(b,"div",{id:"ch"+c.id+g+"Legend"}),a.appendChild(e),e=mv_writeLegendGFXContainer(b,e,f.LegendEntries),f.makeLegend(e,!1))}return a}
function mv_getChartValues(a,b,c){for(var d=a.data,e=0;e<b.Plots.length;e++){var f=b.Plots[e],g=f.Series,h=!1,k=null;f.doLabels(c)&&(k=[],h=!0);switch(f.Type){case "Candlesticks":var q=[],r;g.item(0);for(var n=0;n<g.item(0).Fields.length;n++){var l={},t=f.Series.item("open");try{l.open=Number(d.selectSingleNode("c/"+t.Fields[n]).firstChild.nodeValue)}catch(A){l.open=0}var p=a.Headings.getHeadingByNodeName(t.Fields[n]);h&&mv_makeChartLabelObject(k,n,p);t=f.Series.item("close");if(null==t)0<l.open?
(l.close=0,r=l.open):(l.close=l.open,l.open=0,r=l.close);else try{l.close=Number(d.selectSingleNode("c/"+t.Fields[n]).firstChild.nodeValue)}catch(A){l.close=0}try{l.high=Number(d.selectSingleNode("c/"+f.Series.item("high").Fields[n]).firstChild.nodeValue)}catch(A){l.high=0}try{l.low=Number(d.selectSingleNode("c/"+f.Series.item("low").Fields[n]).firstChild.nodeValue)}catch(A){l.low=0}null!=f.Tooltip&&mv_chartTooltip(f,d,l,p.Alias,r);q.push(l)}b.LegendEntries+=1;g.item(0).Series=q;break;default:for(n=
0;n<g.length();n++){var t=0,m=g.item(n).Fields,q=[];"Pie"!=f.Type&&(b.LegendEntries+=1);var v=!1;if(f.isMultiColored()){var z=b.thSeriesThemes;if("undefined"==typeof g.item(n).Args.fill||dojo.isArray(g.item(n).Args.fill)&&isNaN(g.item(n).Args.fill[0]))v=!0,dojo.isArray(g.item(n).Args.fill)&&isNaN(g.item(n).Args.fill[0])&&(z=g.item(n).Args.fill)}for(var u=0;u<m.length;u++){p=a.Headings.getHeadingByNodeName(m[u]);r=0;try{r=Number(d.selectSingleNode("c/"+m[u]).firstChild.nodeValue)}catch(A){}0==n&&h&&
mv_makeChartLabelObject(k,u,p);l={};l.y=r;f.XValues&&(l.x=u+1);null!=f.Tooltip?mv_chartTooltip(f,d,l,p.Alias,r):l.tooltip=p.Alias+", "+r;v&&(l.fill=z[t].fill,t++,t==z.length&&(t=0));"Pie"==f.Type&&(l.text=p.Alias,b.LegendEntries+=1);q.push(l)}g.item(n).Series=q}}h&&f.Axis.setLabels(k)}}function mv_makeChartLabelObject(a,b,c){var d={};d.value=b+1;d.text=c.Alias;a.push(d)}function mv_paintTool(){mv_clearEvents(!0,"paint");mv_arrangePaint()}
function mv_arrangePaint(){var a=mv_Map.Layers.getLayerObj("MV.Painting");null==a?(mv_declareClassPainting(),a=mv_Map.Layers.getLayerByType("PaintLayer"),a=new MV.Painting(a)):a.reset();mv_showTabContainer(a.FormName)}function mv_exitPaint(){mv_identifyTool()}
function mv_declareClassPainting(){mv_declareClassDrawing();dojo.declare("MV.Painting",[MV.Drawing,MV.CalcGraphs],{"-chains-":{init:"after",start:"after",click:"after",mouseMove:"after",reset:"before",movePoint:"before",destroy:"after"},DoDelete:!1,FeatureType:"Polygon",FeaturePressed:!1,MultiDraw:!0,Precision:6,FormName:"MVpaintForm",DrawState:!0,constructor:function(a){this.Features=[];this.id=a.id;a.LayerObj=this;dojo.style(dojo.byId(this.FormName),"display","inline");this.setSymbol();this.setEventRect(!0);
this.DrawCircle=!1;this.ParMapNode=mv_Map.Root.getElementById(a.id)},init:function(){this.DrawState=!0},start:function(a,b){this.showText(b)},stop:function(){this.setEventRect(!1);this.DrawState=!1;this.setDisabledButtons()},reset:function(){this.IsLocked?1==this.DrawState&&this.setEventRect(!0):(this.DrawState=!0,this.setEventRect(!0),dojo.style(dojo.byId(this.FormName),"display","inline"),this.deleteFeatureList(),this.setDisabledButtons(),this.showText())},destroy:function(){this.deleteFeatureList();
this.setEventRect(!1);this.DrawState=!0;dojo.style(dojo.byId(this.FormName),"display","none");this.showText()},click:function(a){this.DblClick?this.stop():(a=this.addPoint(a),this.Features.push(a),"Point"==this.FeatureType&&this.stop())},mouseMove:function(a){0!=this.ClickCount&&this.showText(a)},setEventRect:function(a){a?mv_Map.Root.getElementById("koordrect").setAttributeNS(null,"pointer-events","all"):mv_Map.Root.getElementById("koordrect").setAttributeNS(null,"pointer-events","none")},alert:function(){mv_alert("Please click on the map to draw the "+
this.FeatureType.toLowerCase()+"!")},setFeatureType:function(a){switch(a){case "Polygon":this.setToggleButtons(!0,!1,!1);break;case "Line":this.setToggleButtons(!1,!0,!1);break;case "Point":this.setToggleButtons(!1,!1,!0)}this.FeatureType=a;this.reset()},setToggleButtons:function(a,b,c){dijit.byId("MVpaintPolygon").set("checked",a);dijit.byId("MVpaintLine").set("checked",b);dijit.byId("MVpaintPoint").set("checked",c)},setDisabledButtons:function(){var a=2<this.hasFeatures()?!1:!0;dijit.byId("MVpaintVertexDelete").set("disabled",
a);a=this.hasFeatures()?!1:!0;dijit.byId("MVpaintFeatureDelete").set("disabled",a);a="Point"==this.FeatureType?!0:!1;a=this.hasFeatures()?a:!0;dijit.byId("MVpaintVertexAdd").set("disabled",a)},addPoint:function(a){var b=this.id+"rec"+this.Features.length;a=mv_Map.getRealMapPoint(a.clientX,a.clientY);a=mv_Map.getMapviewPoint(a);b=this.Symbol.makeSVGNode(mv_Map.Root,mv_Map.LegMapKoeff/mv_Map.Scale,{id:b,cx:a.x,cy:a.y,"pointer-events":"all"});this.ParMapNode.appendChild(b);b.addEventListener("mousedown",
mv_startMovePoint,!1);b.addEventListener("click",mv_deleteVertex,!1);b.addEventListener("mouseup",mv_endMovePoint,!1);return b},hasFeatures:function(){return this.Features.length},startMovePoint:function(a){this.FeaturePressed||(this.FeaturePressed=!0,mv_getRecEle(a).addEventListener("mousemove",mv_doMovePoint,!1),mv_setPanEvent(!1))},movePoint:function(a){if(this.FeaturePressed){var b=mv_Map.getRealMapPoint(a.clientX,a.clientY),b=mv_Map.getMapviewPoint(b),c=mv_getRecEle(a);switch(c.nodeName){case "circle":mv_setAttrSVG(c,
{cx:b.x,cy:b.y})}this.showText(a)}},endMovePoint:function(a){this.FeaturePressed&&(this.FeaturePressed=!1,mv_getRecEle(a).removeEventListener("mousemove",mv_doMovePoint,!1),mv_setPanEvent(!0))},startInsertVertex:function(){for(var a=new MV.Symbol({shape:"line","stroke-width":4,stroke:"red"}),b=0;b<this.Features.length-1;b++){var c=this.Features[b],d=this.Features[b+1],e=c.getAttributeNS(null,"cx"),c=c.getAttributeNS(null,"cy"),f=d.getAttributeNS(null,"cx"),d=d.getAttributeNS(null,"cy"),e=a.makeSVGNode(mv_Map.Root,
mv_Map.LegMapKoeff/mv_Map.Scale,{id:this.id+"line"+(b+1),x1:e,y1:c,x2:f,y2:d});e.addEventListener("click",mv_addVertex,!1);this.ParMapNode.appendChild(e);"Polygon"==this.FeatureType&&b==this.Features.length-2&&(c=this.Features[0],e=c.getAttributeNS(null,"cx"),c=c.getAttributeNS(null,"cy"),e=a.makeSVGNode(mv_Map.Root,mv_Map.LegMapKoeff/mv_Map.Scale,{id:"drawPath",x1:f,y1:d,x2:e,y2:c}),e.addEventListener("click",mv_addVertex,!1),this.ParMapNode.appendChild(e))}},clearInsertVertex:function(){for(var a=
this.ParMapNode.getElementsByTagName("line");0<a.length;)a.item(0).parentNode.removeChild(a.item(0))},addVertex:function(a){var b=this.addPoint(a);a=mv_getRecEle(a).getAttributeNS(null,"id");a=parseInt(a.substring(a.indexOf("line")+4));this.Features.splice(a,0,b);this.clearInsertVertex();this.movePoint()},startDeleteVertex:function(){this.DoDelete=!0},deleteVertex:function(a){if(this.DoDelete){a=mv_getRecEle(a);for(var b=0;b<this.Features.length;b++)if(this.Features[b].getAttributeNS(null,"id")==
a.getAttributeNS(null,"id")){this.deleteItem(b);break}this.DoDelete=!1;this.setDisabledButtons();this.movePoint()}},deleteItem:function(a){a=this.Features.splice(a,1)[0];a.parentNode.removeChild(a)},deleteFeatureList:function(){for(;0<this.Features.length;)this.deleteItem(0)},save:function(a){if(0==this.hasFeatures())this.alert();else{a=[];for(var b=0;b<this.Features.length;b++){var c=this.Features[b],d=parseFloat(c.getAttributeNS(null,"cx")),c=parseFloat(c.getAttributeNS(null,"cy"));a.push(mv_Map.getRealMapX(d).toFixed(this.Precision)+
","+mv_Map.getRealMapY(c).toFixed(this.Precision))}"Polygon"==this.FeatureType&&a.push(a[0]);a=a.join(" ");mv_insertInDB(this.FormName,a);0==this.MultiDraw?mv_exitPaint():(this.reset(),dijit.byId(this.FormName).reset(),"function"==typeof mv_initForm&&mv_initForm())}},setSymbol:function(){this.Symbol=new MV.Symbol({shape:"circle",r:6,fill:"orange",stroke:"none","stroke-width":20})},showText:function(a){"undefined"==typeof a||"Point"==this.FeatureType?(mv_showText("MVArea",""),mv_showText("MVLength",
"")):(mv_showText("MVLength",this.getLength(),a),"Polygon"==this.FeatureType?mv_showText("MVArea",this.getArea(),a):mv_showText("MVArea",""))}})}function mv_savePaint(){mv_Map.Layers.getLayerObj("MV.Painting").save()}function mv_startMovePoint(a){mv_Map.Layers.getLayerObj("MV.Painting").startMovePoint(a)}function mv_doMovePoint(a){mv_Map.Layers.getLayerObj("MV.Painting").movePoint(a)}function mv_endMovePoint(a){mv_Map.Layers.getLayerObj("MV.Painting").endMovePoint(a)}
function mv_setFeatureType(a){mv_Map.Layers.getLayerObj("MV.Painting").setFeatureType(a)}function mv_startAddVertex(){mv_Map.Layers.getLayerObj("MV.Painting").startInsertVertex()}function mv_addVertex(a){mv_Map.Layers.getLayerObj("MV.Painting").addVertex(a)}function mv_startDeleteVertex(){mv_Map.Layers.getLayerObj("MV.Painting").startDeleteVertex()}function mv_deleteVertex(a){mv_Map.Layers.getLayerObj("MV.Painting").deleteVertex(a)}
function mv_deleteFeature(){mv_Map.Layers.getLayerObj("MV.Painting").reset()}
function mv_declareClassSlider(){dojo.declare("MV.Slider",null,{title:"",labels:null,drawTicks:!1,value:1,minimum:0,maximum:100,showButtons:!1,discreteValues:null,sliderLength:"auto",intermediateChanges:!1,onChangeFunc:null,onMouseUpFunc:null,LayerId:"",isSet:!1,horizontal:!0,VectorSettings:null,AnimTimeStep:1500,AnimationButton:null,constructor:function(a){dojo.mixin(this,a)},setDisabled:function(a){this.slider.set("disabled",a);null!=this.AnimationButton&&this.AnimationButton.set("disabled",a)},
getDisabled:function(){return this.slider.get("disabled")},checkValues:function(){if(this.minimum==this.maximum)return mv_alert("min value is the same than max value of the slider: "+this.minimum+" = "+this.maximum),!1;this.value>this.maximum&&(this.value=this.maximum);this.value<this.minimum&&(this.value=this.minimum);null==this.discreteValues&&null!=this.labels&&(this.discreteValues=this.labels.length);return!0},initialize:function(a,b){var c=this.checkValues();this.LayerId=b;this.HandleId=a;this.onChangeFunc=
"mv_slider(this,'"+this.LayerId+"')";if(0!=c){c=document.createElement("div");dojo.byId("MVsliderSlider"+a).appendChild(c);if(null!=this.labels&&0<this.labels.length){if(this.drawTicks){var d=document.createElement("div");c.appendChild(d);1==this.horizontal?new dijit.form.HorizontalRule({count:this.labels.length,style:"height:5px;"},d):new dijit.form.VerticalRule({count:this.labels.length,style:"width:5px;"},d)}d=document.createElement("ol");c.appendChild(d);1==this.horizontal?new dijit.form.HorizontalRuleLabels({labels:this.labels,
style:"font-size:75%;color:gray;margin:2px 0px 15px 0px;"},d):new dijit.form.VerticalRuleLabels({labels:this.labels,style:"font-size:75%;color:gray;margin:0px 10px 0px 0px;"},d)}""!=this.title&&(d=document.createElement("ol"),c.appendChild(d),1==this.horizontal?new dijit.form.HorizontalRuleLabels({labels:Array(this.title),style:"font-size:100%;color:gray;"},d):new dijit.form.VerticalRuleLabels({labels:Array(this.title),style:"font-size:100%;color:gray;"},d));null!=dojo.byId("MVsliderContent")&&dijit.byId("MVsliderContent").destroy();
d="string"==typeof this.sliderLength?this.sliderLength+";":this.sliderLength+"px;";this.slider=1==this.horizontal?new dijit.form.HorizontalSlider({id:"MVsliderContent",value:this.value,minimum:this.minimum,maximum:this.maximum,discreteValues:this.discreteValues,intermediateChanges:this.intermediateChanges,showButtons:this.showButtons,style:"width:"+d},c):new dijit.form.VerticalSlider({id:"MVsliderContent",value:this.value,minimum:this.minimum,maximum:this.maximum,discreteValues:this.discreteValues,
intermediateChanges:this.intermediateChanges,showButtons:this.showButtons,style:"height:"+d},c);var e=this.onChangeFunc;null!=this.onChangeFunc&&(this.slider.onChange=function(a){eval(e)});var f=this.onMouseUpFunc;null!=this.onMouseUpFunc&&(this.slider.onMouseUp=function(a){eval(f)})}}})}
function mv_sliderAnimation(a){mv_setAnimationButton();1==a.checked&&(mv_Slider.slider.value==mv_Slider.slider.maximum?(mv_Slider.slider.reset(),window.setTimeout("mv_AnimMovie()",mv_Slider.AnimTimeStep)):mv_AnimMovie())}function mv_AnimMovie(){0!=mv_Slider.AnimationButton.checked&&(mv_Slider.slider.increment(1),mv_Slider.slider.value<mv_Slider.slider.maximum?window.setTimeout("mv_AnimMovie()",mv_Slider.AnimTimeStep):(mv_Slider.AnimationButton.checked=!1,mv_setAnimationButton()))}
function mv_switchOffLayer(a,b){var c=mv_Map.Layers.item(a);if(null!=c){var d=mv_Map.Root.getElementById(a);b?d.setAttributeNS(null,"display","none"):c.TurnedOn&&d.setAttributeNS(null,"display","inline")}}function mv_colorMapCreateVectorObject(a,b,c,d,e){a.field=b;b=[];for(var f=0;f<e.length;f++){var g={};g.min=c[f];g.max=d[f];g.color=e[f];b.push(g)}a.colors=b}
function mv_colorMapVectorSettings(a){if(a.isVectorLayer()){var b=parseInt(a.VectorSettings.field.substr(1));a.VectorSettings.value=b;null==mv_XMLFileArray[a.id]&&mv_loadAttrTableFile(a.id,!0)}}function _mv_layerOrParentIsTurnedOn(a,b){var c=!0;if(1==b){var d=a.replace("th","").split("-"),e=0,f;dojo.forEach(d,function(a){f=0==e?"th"+a:f+("-"+a);1==c&&(c=_mv_layerOrParentIsTurnedOn(f,!1));e+=1})}d=mv_Map.Layers.item(a);if(0==mv_oExists(d))return!1;1==c&&(c=d.TurnedOn);return c};