dojo.require("dojo.io.script");function mv_declareClassWMSServer(){dojo.declare("MV.WMSServer",null,{Url:"",WMSObject:null,constructor:function(a,b,c){this.id=b;this.WMSObject={};this.Url=c.substring(0,c.indexOf("?")+1);b=c.substring(c.indexOf("?")+1);b=b.split("&");for(c=0;c<b.length;c++){var d=b[c].split("=");this.WMSObject[d[0]]=d[1]}""!=a&&(a=mv_Map.Layers.item(a),mv_oExists(a.BaseGroup)&&a.BaseGroup.addMe(this));this.RootEle=mv_Map}})}
function mv_getWMSLayer(a,b,c){if(0!=a.Visible&&0!=mv_oExists(b)){a=mv_Map.Root.getElementById(a.id);mv_removeSVGele(c);c=mv_makeSVGNode(mv_Map.Root,"image",{id:c,x:mv_Map.CurrentVB.X,y:mv_Map.CurrentVB.Y,width:mv_Map.CurrentVB.Width,height:mv_Map.CurrentVB.Height,preserveAspectRatio:"none"});var d=!1,e=!1;"1.3.0"==b.WMSObject.VERSION&&("epsg:4326"==b.WMSObject.CRS.toLowerCase()&&(e=!0),"epsg:31466"==b.WMSObject.CRS.toLowerCase()&&(e=!0),"epsg:31467"==b.WMSObject.CRS.toLowerCase()&&(e=!0),"epsg:31468"==
b.WMSObject.CRS.toLowerCase()&&(e=!0),"epsg:31469"==b.WMSObject.CRS.toLowerCase()&&(e=!0),"epsg:31492"==b.WMSObject.CRS.toLowerCase()&&(e=!0),"epsg:31493"==b.WMSObject.CRS.toLowerCase()&&(e=!0),"epsg:31494"==b.WMSObject.CRS.toLowerCase()&&(e=!0),"epsg:31495"==b.WMSObject.CRS.toLowerCase()&&(e=!0));"WebMercator"==mv_Map.Projection&&("1.3.0"==b.WMSObject.VERSION?"epsg:4326"==b.WMSObject.CRS.toLowerCase()&&(d=!0):"epsg:4326"==b.WMSObject.SRS.toLowerCase()&&(d=!0));var f=mv_Map.getMapViewbox(d),g="",
h;for(h in b.WMSObject)g+="&"+h+"="+b.WMSObject[h];g=b.Url+g.substring(1)+"&BBOX=";b=f.X+","+f.YMinWMS(d)+","+f.XMax()+","+f.Y;e&&(b=f.YMinWMS(d)+","+f.X+","+f.Y+","+f.XMax());g+=b;b=mv_Map.CurrentExt.Width;h=mv_Map.CurrentExt.Height;d&&(mv_Map.CurrentExt.Height>mv_Map.CurrentExt.Width?b=f.Width*mv_Map.CurrentExt.Height/Math.abs(f.Height):h=Math.abs(f.Height)*mv_Map.CurrentExt.Width/f.Width);g=g+"&width="+parseInt(b);g=g+"&height="+parseInt(h);c.setAttributeNS("http://www.w3.org/1999/xlink","href",
g);a.appendChild(c)}}function mv_declareClassWMTSServer(){dojo.declare("MV.WMTSServer",null,{ScaleDenominators:[4E3,3750,3500,3250,3E3,2750,2500,2250,2E3,1750,1500,1250,1E3,750,650,500,250,100,50,20,10,5,2.5,2,1.5,1,.5,.25,.1],xMin:42E4,yMin:3E4,xMax:9E5,yMax:35E4,MaxZoom:26,SubDomains:null,Copyright:"",Key:null,BrandLogo:null,constructor:function(a,b,c){this.id=b;this.Url=c;""!=a&&(a=mv_Map.Layers.item(a),mv_oExists(a.BaseGroup)&&a.BaseGroup.addMe(this));this.RootEle=mv_Map}})}
function mv_getWMTSLayer(a,b,c){if(0==a.Visible)return!0;if(0!=mv_oExists(b)){for(var d=b.RootEle.getMapViewbox(!1),e=mv_getWMTSZoom(b.ScaleDenominators,b.MaxZoom),f=mv_makeSVGNode(b.RootEle.Root,"g",{id:c}),g=b.xMax-b.xMin,h=b.yMax-b.yMin,l=mv_WMTSCol2tile(d.X,b.xMin,g,b.ScaleDenominators[e]),g=mv_WMTSCol2tile(d.XMax(),b.xMin,g,b.ScaleDenominators[e]),k=mv_WMTSRow2tile(d.Y,b.yMax,h,b.ScaleDenominators[e]),d=mv_WMTSRow2tile(d.Y-d.Height,b.yMax,h,b.ScaleDenominators[e]),h=256*b.ScaleDenominators[e]*
mv_Map.NormalizeFactor,n=256*b.ScaleDenominators[e]*mv_Map.NormalizeFactor,p=b.xMin*mv_Map.NormalizeFactor-mv_Map.XOrigin+h*l,m=-1*(b.yMax*mv_Map.NormalizeFactor-mv_Map.YOrigin)+h*k,r=b.ScaleDenominators[e]*mv_Map.NormalizeFactor*.2,t=h+2*r,x=n+2*r,q=p,u=0;k<=d;k++){for(var y=m-r,w=l;w<=g;w++){var v=mv_makeSVGNode(b.RootEle.Root,"image",{x:p-r,y:y,width:t,height:x,preserveAspectRatio:"none"}),z=b.Url;mv_oExists(b.SubDomains)&&(z=z.replace(/{subdomain}/,b.SubDomains[u]),u++,u=u==b.SubDomains.length?
0:u++);1==mv_isIE()?v.addEventListener("SVGError",function(){this.setAttributeNS(null,"display","none")},!1):v.addEventListener("error",function(){this.setAttributeNS(null,"display","none")},!1);v.setAttributeNS("http://www.w3.org/1999/xlink","href",mv_getWMTSURL(b,z,w,k,e));f.appendChild(v);p+=h}m+=n;p=q}(c=root.getElementById(c))?b.RootEle.Root.getElementById(a.id).replaceChild(f,c):b.RootEle.Root.getElementById(a.id).appendChild(f);a=dojo.byId("MVCredit");mv_oExists(a)&&(a.innerHTML=mv_Doc.Copyright?
b.Copyright+" - "+mv_Doc.Copyright:b.Copyright)}}function mv_getWMTSURL(a,b,c,d,e){b=b.replace(/{z}/,e);b=b.replace(/{x}/,c);b=b.replace(/{y}/,d);return b=b.replace(/{key}/,a.Key)}function mv_WMTSCol2tile(a,b,c,d){a=Math.floor((a-b)/(256*d));a=Math.max(0,a);return a=Math.min(Math.floor(c/(256*d)),a)}function mv_WMTSRow2tile(a,b,c,d){a=Math.floor((b-a)/(256*d));a=Math.max(0,a);return a=Math.min(Math.floor(c/(256*d)),a)}
function mv_getWMTSZoom(a,b){var c=mv_Map.mapScale(),d=b,c=.0254*c/96;for(i=0;i<a.length;i++)if(a[i]<c){d=i;break}return Math.min(d,b)}
function mv_declareClassBingMapServer(){dojo.declare("MV.BingMapServer",null,{MaxZoom:22,Url:"",SubDomains:null,BrandLogo:null,constructor:function(a,b,c,d,e){this.layerId=a;this.id=b;this.Key=c;this.ImagerySet=d;this.Copyright=e;""!=a&&(a=mv_Map.Layers.item(a),mv_oExists(a.BaseGroup)&&a.BaseGroup.addMe(this));this.RootEle=mv_Map},initialize:function(){mv_Doc.BingMapPara=this;mv_declareClassWebService();(new MV.WebService({URL:"http://dev.virtualearth.net/REST/V1/Imagery/Metadata/"+this.ImagerySet+
"/"})).fire2({key:this.Key,mv:"v1",jsonp:"mv_initializeBingTileServer"})}})}function mv_getBingMapLayer(a,b,c){""==b.Url?b.initialize():mv_getOSMLayer(a,b,c)}
function mv_initializeBingTileServer(a){if(0!=a.resourceSets.length){var b=a.resourceSets[0].resources[0],c=mv_Doc.BingMapPara;c.SubDomains=b.imageUrlSubdomains;c.Url=b.imageUrl;c.BrandLogo={};c.BrandLogo.width=93;c.BrandLogo.height=29;c.BrandLogo.logo=a.brandLogoUri;c.BrandLogo.link="http://www.bing.com/maps/";a=mv_Map.Layers.item(c.layerId);mv_getOSMLayer(a,c,a.id+"BaseMap");mv_Doc.BingMapPara=null}}
function mv_declareClassMapTileServer(){dojo.declare("MV.MapTileServer",null,{type:"default",MaxZoom:18,SubDomains:null,Copyright:"",Key:null,BrandLogo:null,constructor:function(a,b,c){this.id=b;this.Url=c;""!=a&&(a=mv_Map.Layers.item(a),mv_oExists(a.BaseGroup)&&a.BaseGroup.addMe(this));this.RootEle=mv_Map;0<=c.indexOf("arcgisonline")&&(this.BrandLogo={},this.BrandLogo.width=43,this.BrandLogo.height=25,this.BrandLogo.logo="http://js.arcgis.com/3.12/esri/images/map/logo-sm.png",this.BrandLogo.link=
"http://www.esri.com/")}})}
function mv_getOSMLayer(a,b,c){if(0==a.Visible)return!0;if(0!=mv_oExists(b)){for(var d=b.RootEle.getMapViewbox(!0),e=mv_getOSMZoom(d,b.RootEle,b.MaxZoom),f=mv_makeSVGNode(b.RootEle.Root,"g",{id:c}),g=mv_OSMlong2tile(d.X,e),h=mv_OSMlong2tile(d.XMax(),e),l=mv_OSMlat2tile(d.Y,e),d=mv_OSMlat2tile(d.YMin(),e),k=mv_OSMtile2MapViewX(g,e),n=mv_OSMtile2MapViewX(g+1,e),p=mv_OSMtile2MapViewY(l,e),m=mv_OSMtile2MapViewY(l+1,e),n=n-k,m=m-p,r=n+2*n/256,t=m+2*m/256,x=k,q=0,u=l;u<=d;u++){for(var y=p-m/256,w=g;w<=
h;w++){var l=mv_makeSVGNode(b.RootEle.Root,"image",{x:k-n/256,y:y,width:r,height:t,preserveAspectRatio:"none"}),v=b.Url;mv_oExists(b.SubDomains)&&(v=v.replace(/{subdomain}/,b.SubDomains[q]),q++,q=q==b.SubDomains.length?0:q++);1==mv_isIE()?l.addEventListener("SVGError",function(){this.setAttributeNS(null,"display","none")},!1):l.addEventListener("error",function(){this.setAttributeNS(null,"display","none")},!1);l.setAttributeNS("http://www.w3.org/1999/xlink","href",mv_getOSMTileURL(b,v,w,u,e));f.appendChild(l);
k+=n}p+=m;k=x}c=root.getElementById(c);null!=c?b.RootEle.Root.getElementById(a.id).replaceChild(f,c):b.RootEle.Root.getElementById(a.id).appendChild(f);if(a=dojo.byId("MVCredit"))a.innerHTML=mv_Doc.Copyright?b.Copyright+" - "+mv_Doc.Copyright:b.Copyright;(a=dojo.byId("MVBLogo"))?a.innerHTML="":a=mv_makeNode(document,"div",{id:"MVBLogo",style:"position:absolute;bottom:20px;right:5px;opacity:0.8;"});mv_oExists(b.BrandLogo)&&(l=mv_makeNode(document,"img",{src:b.BrandLogo.logo,width:"100%",height:"100%"}),
b=mv_makeNode(document,"a",{href:b.BrandLogo.link,target:"_blank"}),b.appendChild(l),a.appendChild(b),dojo.byId("MVmap").appendChild(a))}}function mv_getOSMTileURL(a,b,c,d,e){switch(a.declaredClass){case "MV.BingMapServer":a="";for(var f=Math.pow(2,e)/2,g=0,h=0;h<e;h++)c>=f&&(g++,c-=f),d>=f&&(g++,g++,d-=f),a+=g.toString(),f/=2,g=0;b=b.replace(/{quadkey}/,a);break;case "MV.MapTileServer":b=b.replace(/{z}/,e),b=b.replace(/{x}/,c),b=b.replace(/{y}/,d),b=b.replace(/{key}/,a.Key)}return b}
function mv_OSMlong2tile(a,b){var c=Math.floor((a+180)/360*Math.pow(2,b)),c=Math.max(0,c);return c=Math.min(Math.pow(2,b)-1,c)}function mv_OSMlat2tile(a,b){var c=Math.floor((1-Math.log(Math.tan(a*Math.PI/180)+1/Math.cos(a*Math.PI/180))/Math.PI)/2*Math.pow(2,b)),c=Math.max(0,c);return c=Math.min(Math.pow(2,b)-1,c)}function mv_OSMtile2MapViewX(a,b){a=a/Math.pow(2,b)*360-180;return mv_Map.getMapviewX(a)}
function mv_OSMtile2MapViewY(a,b){a=Math.PI-2*Math.PI*a/Math.pow(2,b);a=180/Math.PI*Math.atan(.5*(Math.exp(a)-Math.exp(-a)));return mv_Map.getMapviewY(a)}function mv_getOSMZoom(a,b,c){b=b.CurrentVB.Width/b.CurrentExt.Width*256;for(var d=1,e=mv_OSMlong2tile(a.X,d),f=mv_OSMtile2MapViewX(e,d),e=mv_OSMtile2MapViewX(e+1,d),f=e-f;f>b&&d<c;)d+=1,e=mv_OSMlong2tile(a.X,d),f=mv_OSMtile2MapViewX(e,d),e=mv_OSMtile2MapViewX(e+1,d),f=e-f;return d}
function mv_initOSMNominatim(a){mv_declareClassMultilingualism();mv_declareClassWebService();mv_declareClassOSMNominatim();mv_OSMNominatim=new MV.OSMNominatim(a)}
function mv_declareClassOSMNominatim(){dojo.declare("MV.OSMNominatim",null,{VB:"",Top:90,Bottom:-90,Left:-180,Right:180,Unit:"k",Locale:"en_US",ShapeFormat:"cmp",Generalize:10,RouteType:"fastest",RouteColors:{},LayerId:"",NominatimId:"",TxtAddr1:"",TxtAddr2:"",TxtTitle:"",TxtPresentLoc:"Present location",InputWidth:250,constructor:function(a){this.Texts=new MV.JSONTextSettings(mv_Doc.BaseURL+"embfiles/osmterms_json.js");var b=dojo.byId("MVaddress1");mv_oExists(b)&&(this.InputWidth=dojo.style(b,"width"));
mv_oExists(a)&&(this.LayerId=a,a=mv_Map.Layers.item(a),a.IdentifyObj.Container="MVtools",a.IdentifyObj.DeleteRecInMap=!0,this.RouteColors.fastest="tomato",this.RouteColors.shortest="blue",this.RouteColors.pedestrian="green",this.RouteColors.multimodal="cyan",this.RouteColors.bicycle="purple",mv_XMLFileArray[this.LayerId]=new MV.List,this.setLang(mv_Doc.Lang))},doNominatim:function(a){this.NominatimId=a.getAttribute("id");this.viewNum=parseInt(this.NominatimId.substring(this.NominatimId.indexOf("MVaddress")+
9));a=a.value;"MVaddress1"==this.NominatimId?this.TxtAddr1=a:this.TxtAddr2=a;if(!mv_Doc.IsMobile||a!=this.TxtPresentLoc&&""!=a){var b=new MV.WebService({URL:"http://nominatim.openstreetmap.org/search"});""==this.VB?b.fire2({q:a,format:"jsonv2",polygon:0,addressdetails:1,json_callback:"mv_startNominatim",email:"info@uismedia.de","accept-language":mv_Doc.Lang}):b.fire2({q:a,format:"jsonv2",polygon:0,addressdetails:1,json_callback:"mv_startNominatim",email:"info@uismedia.de","accept-language":mv_Doc.Lang,
viewbox:this.VB})}else navigator.geolocation?navigator.geolocation.getCurrentPosition(mv_callDeviceLocationNominatim,mv_errorDeviceLocationNominatim,mv_getLocationOption()):this.doReverseGeocoding(48.003961,9.623895);return!1},doReverseGeocoding:function(a,b){(new MV.WebService({URL:"http://nominatim.openstreetmap.org/reverse"})).fire2({lat:a,lon:b,format:"jsonv2",addressdetails:1,json_callback:"mv_startNominatim",email:"info@uismedia.de",zoom:18,"accept-language":mv_Doc.Lang})},doRoutingToPoi:function(){navigator.geolocation&&
navigator.geolocation.getCurrentPosition(mv_callDeviceLocationNominatim,mv_errorDeviceLocationNominatim,mv_getLocationOption())},doRouting:function(){if("none"==dojo.style(dojo.byId("MVrouting"),"display"))dojo.style(dojo.byId("MVrouting"),"display","inline");else{var a=this.RouteType;dojo.query("input[name='MVRoute']").forEach(function(b){1==b.checked&&(a=b.value)});this.RouteType=a;var b=this.testRouting("MVaddress1");if(0!=mv_oExists(b)){var c=this.testRouting("MVaddress2");0!=mv_oExists(c)&&this.doRouting2(b[5],
b[4],c[5],c[4],this.TxtAddr1+" -> "+this.TxtAddr2)}}},testRouting:function(a){var b=dijit.byId(a),c=this.checkRouteAlertTxt1(b,a);if(0==mv_oExists(c)||0==this.checkRouteAlertTxt2(b.get("value"),c))return null;mv_removeSVGele("mvVisPoint"+a);return b.get("value").split(",")},doRouting2:function(a,b,c,d,e){this.TxtTitle=e;mv_declareClassRouteObject();var f=a+","+b,g=c+","+d;e=this.Generalize;a=new MV.Point(parseFloat(b),parseFloat(a));c=new MV.Point(parseFloat(d),parseFloat(c));2E3>=a.distance(c,!0)&&
(e=2);a.equal(c)||(c="http://open.mapquestapi.com/directions/v2/route?key=Fmjtd%7Cluubn1u12q%2Cr2%3Do5-90bahf&from="+f+("&to="+g),c+="&unit="+this.Unit,c+="&locale="+this.Locale,c+="&shapeFormat="+this.ShapeFormat,c+="&routeType="+this.RouteType,c+="&generalize="+e,c+="&callback=mv_startRouting",(new MV.WebService({URL:c})).fire2({}))},showPointOnRouteMobile:function(a,b){this.showPointOnRoute(a,b);mv_zoomToExtent(a,a,b,b,20);mv_Doc.setMapTab()},showPointOnRoute:function(a,b){var c=new MV.Symbol({shape:"img",
src:"symbols/onroute.png",width:17,height:17});mv_drawPoint("mvVisPoint",!1,a,b,c)},clearNominatim:function(a){a=a.id.substring(0,10);var b="",c=dijit.byId(a);if(mv_oExists(c)&&0==mv_Doc.IsMobile){var b="MVaddress1"==a?this.TxtAddr1:this.TxtAddr2,d=dojo.byId(a+"Form"),e=dojo.byId(a).nextSibling;c.destroy();b=mv_makeNode(document,"input",{value:b,id:a,type:"text","class":"formElem",name:"MVaddress",style:"width:"+this.InputWidth+"px"});d.insertBefore(b,e)}this.clearAlertTxt(a+"Alert");mv_removeSVGele("mvVisPoint"+
a)},clearAddress:function(a){a.value==this.TxtPresentLoc&&(a.value="")},setVB:function(a){this.VB=a;a=a.split(",");4==a.length&&(this.Left=parseFloat(a[0]),this.Top=parseFloat(a[1]),this.Right=parseFloat(a[2]),this.Bottom=parseFloat(a[3]))},getRouteColor:function(a){return mv_oExists(this.RouteColors[a])?this.RouteColors[a]:"black"},setAlertTxt:function(a,b){if(0==mv_oExists(a))mv_alert(b);else{var c=mv_makeNode(document,"img",{src:mv_Doc.BaseURL+"pictures/attention.png"});a.appendChild(c);a.innerHTML+=
b}},clearAlertTxt:function(a){a=dojo.byId(a);mv_oExists(a)&&(a.innerHTML="");return a},checkRouteAlertTxt1:function(a,b){var c=this.clearAlertTxt(b+"Alert");return 0==mv_oExists(a)?(this.setAlertTxt(c,this.Texts.getText("routing.insert_address","Please enter an address and then press the Return button.")),null):c},checkRouteAlertTxt2:function(a,b){return""==a?(this.setAlertTxt(b,this.Texts.getText("routing.choose_from_list","Please choose a location from the list(s)!")),!1):!0},clearRouting:function(){for(var a=
mv_XMLFileArray[this.LayerId].length(),b=0;b<a;b++){var c=mv_XMLFileArray[this.LayerId].deleteItem(a-1-b);this.clearRoutingMapFeat(c);mv_deleteTP(c[0].id)}mv_removeSVGele("mvVisPoint")},clearRoutingMapFeat:function(a){mv_removeSVGele(a[0].id);mv_removeSVGele(a[0].id+"mar1");mv_removeSVGele(a[0].id+"mar2")},clearRoutingRec:function(a){a=mv_XMLFileArray[this.LayerId].deleteItem(a);null!=a&&this.clearRoutingMapFeat(a)},setLang:function(){switch(mv_Doc.Lang){case "de":this.Locale="de_DE";break;case "en":this.Locale=
"en_US"}},print:function(){return mv_oExists(mv_XMLFileArray[this.LayerId])&&0<mv_XMLFileArray[this.LayerId].length()?mv_XMLFileArray[this.LayerId]:null}})}
function mv_declareClassRouteObject(){dojo.declare("MV.RouteObject",null,{Status:"route",constructor:function(a){dojo.mixin(this,a)},getRecIds:function(){return Array(this.id)},getName:function(){return this.Name},getVBString:function(a){return this.VB.getVBString(a)},deleteMe:function(){1==mv_Map.Layers.item(this.themaId).IdentifyObj.DeleteRecInMap&&(mv_oExists(this.ele)&&this.ele.parentNode.removeChild(this.ele),mv_removeSVGele("mvVisPoint"))}})}
function mv_startNominatim(a){var b=mv_OSMNominatim.clearAlertTxt(mv_OSMNominatim.NominatimId+"Alert"),c=!1;dojo.isArray(a)?0==a.length&&(mv_OSMNominatim.setAlertTxt(b,mv_OSMNominatim.Texts.getText("OSM.noRecFound","No record found!")),c=!0):(0==mv_oExists(a.lat)&&(mv_OSMNominatim.setAlertTxt(b,mv_OSMNominatim.Texts.getText("OSM.noRecFound","No record found!")),c=!0),a=Array(a));if(!c){for(var b=[],c=[],d=0;d<a.length;d++){var e=a[d],f=mv_getOSMText(e).join(", "),f=f.replace(/\(land mass\)/,""),f=
f.replace(/\(Landmasse\)/,"");dojo.isOpera&&(f=mv_changeUmlaut2(f));var g="",g=mv_OSMNominatim.Texts.search(e.type,"");""==g&&(g=mv_OSMNominatim.Texts.search(e.category,e.category));f=g+": "+f;if(!(0<=dojo.indexOf(b,f))){var h=e.lon,l=e.lon,k=e.lat,n=e.lat;mv_oExists(e.boundingbox)&&(h=e.boundingbox[2],l=e.boundingbox[3],k=e.boundingbox[0],n=e.boundingbox[1]);var p=e.lat,m=e.lon;""!=mv_OSMNominatim.VB&&(p<mv_OSMNominatim.Bottom||p>mv_OSMNominatim.Top)&&(m<mv_OSMNominatim.Left||m>mv_OSMNominatim.Right)||
(g={},g.label=f,g.id=h+","+l+","+k+","+n+","+m+","+p,mv_Doc.IsMobile&&(h=mv_OSMNominatim.Texts.getIcon(e.type),""==h&&(h=mv_OSMNominatim.Texts.getIcon(e.category)),h=""==h?"pictures/osm/empty.png":"pictures/osm/"+h+".png",g.icon=h,g.variableHeight=!0,mv_mobileRoutingListitemFunc(g)),c.push(g),b.push(f))}}1<c.length&&(g={},g.label="..."+mv_OSMNominatim.Texts.getText("routing.choose","Please choose...."),g.id="",g.header="true",c.unshift(g));a=new dojo.data.ItemFileReadStore({data:{identifier:"id",
label:"label",items:c}});a=new dijit.form.Select({id:mv_OSMNominatim.NominatimId,name:"MVaddress",store:a,onChange:function(){mv_zoomNominatim(this.get("value"),mv_OSMNominatim.NominatimId)}},mv_OSMNominatim.NominatimId);dojo.addClass(a.domNode,"MVselRoute");a.startup()}}function mv_mobileRoutingListitemFunc(a){var b="mv_mobileAddressEnableButtons('"+mv_OSMNominatim.NominatimId+"',false); ";a.onClick=function(){eval(b)}}
function mv_mobileAddressEnableButtons(a,b){dijit.byId(a+"ZoomTo").set("disabled",b)}function mv_mobileAddressTransition(a,b,c,d){dijit.byId(a).performTransition(b,d,"slide",null);a=dijit.byId("MVaddressTabBar").getChildren()[c];mv_oExists(a)&&a.set("selected",!0)}
function mv_startRouting(a){var b=mv_OSMNominatim.clearAlertTxt("MVaddressChoice");if(0==mv_oExists(a.route.shape)||0==mv_oExists(a.route.shape.shapePoints))mv_OSMNominatim.setAlertTxt(b,mv_OSMNominatim.Texts.getText("routing.noRouteFound","No result."));else{var c=mv_decompress(a.route.shape.shapePoints,5);if(!(4>c.length)){var d,e;e=mv_Map.getMapviewY(c.shift());d=mv_Map.getMapviewX(c.shift());for(var f=e,g=d,h=b=d,l=e,k=e,n="M"+d+" "+e;0<c.length;)e=mv_Map.getMapviewY(c.shift()),d=mv_Map.getMapviewX(c.shift()),
n=n+"L"+d+" "+e,b=Math.min(b,d),h=Math.max(h,d),l=Math.min(l,e),k=Math.max(k,e);var p=d,m=a.route.options.routeType.toLowerCase();d=mv_OSMNominatim.LayerId;var c=d+"rec"+mv_XMLFileArray[d].length(),r=0;a.route.distance&&(r=a.route.distance);var t="";if(a.route.options.unit)switch(t=a.route.options.unit,t.toUpperCase()){case "K":t="km";break;case "M":t="miles"}var x=mv_OSMNominatim.TxtTitle+" ("+mv_OSMNominatim.Texts.getText("routing."+m,m)+")",q=mv_OSMNominatim.Texts.getText("routing."+m,m)+" ("+
r.toFixed(2)+" "+t+")",q=mv_makeSVGNode(mv_Map.Root,"g",{id:c+"g",onmouseover:"parent.mv_mapTipOver(evt,'"+q+"');"}),u=mv_Map.LegMapKoeff/mv_Map.Scale,y=new MV.Symbol({shape:"path",stroke:mv_OSMNominatim.getRouteColor(m),"stroke-width":3}),n=y.makeSVGNode(mv_Map.Root,u,{id:c,d:n});n.setAttributeNS(null,"pointer-events","visibleStroke");q.appendChild(n);var y=new MV.Symbol({shape:"img",src:"symbols/MVaddress1.png",width:17,height:17}),w=u*y.height,v=u*y.width,f=y.makeSVGNode(mv_Map.Root,u,{id:c+"mar1",
x:g-v/2,y:f-w/2,width:v,height:w});q.appendChild(f);y=new MV.Symbol({shape:"img",src:"symbols/MVaddress2.png",width:17,height:17});f=y.makeSVGNode(mv_Map.Root,u,{id:c+"mar2",x:p-v/2,y:e-w/2,width:v,height:w});q.appendChild(f);mv_Map.Root.getElementById(d).appendChild(q);f=new MV.Viewbox;try{var z=n.getBBox();f.X=z.x;f.Y=z.y;f.Width=z.width;f.Height=z.height}catch(A){f.X=b,f.Y=l,f.Width=h-b,f.Height=k-l}a=new MV.RouteObject({id:c,themaId:d,ele:q,Name:x,VB:f,Unit:t,Length:r,Legs:a.route.legs,RouteType:m});
mv_XMLFileArray[d].addMe(a);mv_identify(c,"route");mv_Doc.IsMobile||mv_zoomToExtent2(f.getVBString(20))}}}
function mv_makeIdentifyRouteNode(a,b,c,d){var e;c=mv_Doc.IsMobile?mv_OSMNominatim.Texts.getText("routing.help_positionOnRoadMobile","When clicking on a row in the table the position will be shown on the map."):mv_OSMNominatim.Texts.getText("routing.help_positionOnRoad","Watch location on map when moving mouse over the table.");e=mv_makeFullNode(b,"p",{},c);a.appendChild(e);0!=d.Length&&(e=mv_makeFullNode(b,"p",{},mv_OSMNominatim.Texts.getText("routing.length","Length")+": "+d.Length.toFixed(2)+" "+
d.Unit),a.appendChild(e));e=mv_makeFullNode(b,"p",{},mv_OSMNominatim.Texts.getText("routing.route_type","Type of route")+": "+mv_OSMNominatim.Texts.getText("routing."+d.RouteType,d.RouteType));a.appendChild(e);c=mv_makeNode(b,"table",{"class":"identify"});for(var f,g,h=d.Legs,l=!0,k=0,n=0,p=h.length;n<p;n++)for(var k=k+(h[n].maneuvers.length-1),m=0,r=h[n].maneuvers.length;m<r;m++){f=h[n].maneuvers[m];g=[];var t=mv_Map.getMapviewY(f.startPoint.lat),x=mv_Map.getMapviewX(f.startPoint.lng);f.iconUrl&&
(e=f.iconUrl,1==l&&(e=mv_Doc.BaseURL+"symbols/MVaddress1.png",l=!1),m==k&&(e=mv_Doc.BaseURL+"symbols/MVaddress2.png"),e=mv_makeNode(b,"img",{src:e}),g.push(e));m!=k?g.push(f.narrative):g.push(mv_OSMNominatim.Texts.getText("routing.welcome_destination","Welcome to your destination."));d.Unit&&f.distance?g.push(f.distance.toFixed(2)+" "+d.Unit):g.push("");f=mv_makeNode(b,"tr",{});for(e=0;e<g.length;e++)tdNode=mv_makeFullNode(b,"td",{"class":"identify"},g[e]),f.appendChild(tdNode);mv_Doc.isSmartPhoneLayout()?
mv_setAttr(f,{onclick:"mv_OSMNominatim.showPointOnRouteMobile("+x+","+t+");"}):mv_setAttr(f,{onmouseover:"mv_OSMNominatim.showPointOnRoute("+x+","+t+");",onmouseout:"mv_removeSVGele('mvVisPoint');"});dojo.style(f,"cursor","pointer");c.appendChild(f)}a.appendChild(c);return a}function mv_writeTRNode(a,b){for(var c=mv_makeNode(a,"tr",{}),d,e=0;e<b.length;e++)d=mv_makeFullNode(a,"td",{"class":"identify"},b[e]),c.appendChild(d);return c}
function mv_getOSMTextAdmin(a,b){mv_oExists(b.address.city)&&a.push(b.address.city);mv_oExists(b.address.county)&&a.push(b.address.county);mv_oExists(b.address.state)&&a.push(b.address.state);mv_oExists(b.address.country)&&a.push(b.address.country)}
function mv_getOSMText(a){var b=a.type;""==b&&(b=a.category);var c=[];switch(b){case "administrative":mv_getOSMTextAdmin(c,a);break;case "village":mv_oExists(a.address.village)&&c.push(a.address.village);mv_getOSMTextAdmin(c,a);break;case "suburb":mv_oExists(a.address.suburb)&&c.push(a.address.suburb);mv_getOSMTextAdmin(c,a);break;case "hamlet":mv_oExists(a.address.hamlet)&&c.push(a.address.hamlet);mv_getOSMTextAdmin(c,a);break;case "town":mv_oExists(a.address.town)&&c.push(a.address.town);mv_getOSMTextAdmin(c,
a);break;case "residential":mv_oExists(a.address.road)&&c.push(a.address.road);mv_getOSMTextAdmin(c,a);break;default:c.push(a.display_name)}return c}function mv_changeUmlaut2(a){return a=a.replace(/\u00c3\u0178/g,"\u00df")}function mv_zoomListItemSelect_alt(a){a=a.id.substring(0,a.id.indexOf("ZoomTo"));var b=dijit.byId(a+"List");if(0!=b.hasChildren()){for(var b=b.getChildren(),c="",d=0;d<b.length;d++)if(b[d].selected){c=b[d].id;break}mv_zoomNominatim(c,a)}}
function mv_zoomNominatim(a,b){if(""!=a){var c=a.split(","),d=parseFloat(c[0]),e=parseFloat(c[1]),f=parseFloat(c[2]),g=parseFloat(c[3]),h=parseFloat(c[4]),c=parseFloat(c[5]);mv_zoomToLatLng(d,e,f,g);d=mv_Map.getMapviewX(h);e=mv_Map.getMapviewY(c);f=new MV.Symbol({shape:"img",src:"symbols/"+b+".png",width:17,height:17});mv_drawPoint("mvVisPoint"+b,!1,d,e,f)}}
function mv_decompress(a,b){b=Math.pow(10,-b);for(var c=a.length,d=0,e=0,f=0,g=[];d<c;){var h,l=0,k=0;do h=a.charCodeAt(d++)-63,k|=(h&31)<<l,l+=5;while(32<=h);e+=k&1?~(k>>1):k>>1;k=l=0;do h=a.charCodeAt(d++)-63,k|=(h&31)<<l,l+=5;while(32<=h);f+=k&1?~(k>>1):k>>1;g.push(e*b);g.push(f*b)}return g}function mv_getPhotoLayer(){var a=dijit.byId("MVtoolbar.photos").checked,b=mv_Map.Layers.getLayerByType("PhotoLayer");mv_changeLayerVis2(a,b,!0)}
function mv_doPhotoLayer(a){0==mv_oExists(a.LayerObj)?mv_SendRequestJson(mv_Doc.BaseURL+"dbfiles/pictures."+mv_Doc.DBExt+"?variables="+a.id+";"+mv_Doc.BaseURL,mv_handlePhotoLayerDB):a.LayerObj.fillClusters()}function mv_handlePhotoLayerDB(a){var b=a.shift(),b=mv_Map.Layers.item(b);b.LayerObj=new MV.MarkerClusters(b.id);b.LayerObj.Type="Pictures";b.LayerObj.DataType="DBPictures";b.LayerObj.init(a);b.LayerObj.fillClusters()}
function mv_declareClassJsonObject(){dojo.declare("MV.JsonObject",null,{Status:"wiki",constructor:function(a){dojo.mixin(this,a)},getRecIds:function(){return Array(this.id)},getName:function(){return"wiki"==this.Status?this.data.title:"Panoramio "+this.data.photo_id},getVBString:function(a){if("wiki"==this.Status)var b=mv_Map.getMapviewY(this.data.lat),c=mv_Map.getMapviewX(this.data.lng);else b=mv_Map.getMapviewY(this.data.latitude),c=mv_Map.getMapviewX(this.data.longitude);return c+","+c+","+b+","+
b+","+a}})}function mv_declareClassWebService(){dojo.declare("MV.WebService",null,{constructor:function(a){dojo.safeMixin(this,a)},fire:function(a,b,c){mv_loadJSONDoc(this.URL,a,b,c);window.status=""},fire2:function(a){mv_loadJSONDoc2(this.URL,a);window.status=""}})}function mv_getPanoramioLayerBB(){mv_removeSVGele("PrLayer");var a=dijit.byId("MVtoolbar.panoramio").checked,b=mv_Map.Layers.getLayerByType("PanoramioLayer");mv_changeLayerVis2(a,b,!0)}
function mv_doPanoramioBB(a){var b=mv_Map.getMapViewbox("WebMercator"==mv_Map.Projection?!0:!1);try{(new MV.WebService({URL:"http://www.panoramio.com/map/get_panoramas.php"})).fire({set:"public",from:"0",to:a.imgCount,maxy:b.Y,miny:b.YMin(),maxx:b.XMax(),minx:b.X,size:"mini_square",mapfilter:"true"},mv_insertPanoramioLayer,mv_errorWikipedia)}catch(c){}}
function mv_insertPanoramioLayer(a,b){var c=mv_Map.Layers.getLayerByType("PanoramioLayer").id,d=mv_Map.Root.getElementById(c),e=null;mv_oExists(a)&&(e=a.photos);if(0!=mv_oExists(e)){mv_XMLFileArray[c]=new MV.List;mv_removeSVGele("PrLayer");for(var f=mv_makeSVGNode(mv_Map.Root,"g",{id:"PrLayer"}),g=mv_Map.CurrentVB.Width/mv_Map.CurrentExt.Width*18,h,l=0;l<mv_Map.Identifys.length();++l){var k=mv_Map.Identifys.List[l].data,n=!0;if(mv_oExists(k)&&"MV.JsonObject"==k.declaredClass){for(var p=0;p<e.length;p++)if(k.data.photo_file_url==
e[p].photo_file_url){n=!1;break}n&&(mv_XMLFileArray[c].addMe(k),h=mv_LoadedPOIsSettings(k,g,"pan"),f.appendChild(h))}}for(l=0;l<e.length;l++){var k=e[l],n=k.photo_title.replace(/'/g,""),p=c+"rec"+k.photo_id,m=g;0==l%10&&(m=2*g);var r=g/3,t=mv_Map.getMapviewY(k.latitude)-m/2,x=mv_Map.getMapviewX(k.longitude)-m/2,q=mv_makeSVGNode(mv_Map.Root,"g",{id:p+"g"});h=new MV.Symbol({shape:"rect",fill:"white",stroke:"white",width:m+r,height:m+r});h=h.makeSVGNode(mv_Map.Root,1,{x:x,y:t});q.appendChild(h);h=new MV.Symbol({shape:"img",
src:k.photo_file_url,width:m,height:m});h=h.makeSVGNode(mv_Map.Root,1,{id:p,x:x+r/2,y:t+r/2,width:m,height:m,onmouseover:"parent.mv_mapTipOver(evt,'"+n+"');"});q.appendChild(h);f.appendChild(q);k=new MV.JsonObject({id:p,themaId:c,data:k,ele:h,Status:"pano"});mv_XMLFileArray[c].addMe(k)}d.appendChild(f);window.status=""}}
function mv_makeIdentifyPanoramioNode(a,b,c,d){var e,f;e="identify";mv_Doc.IsMobile&&(e="identifyMobile");var g=mv_makeNode(b,"table",{"class":e}),h=d.data;c&&(e=mv_makeNode(b,"tr",{}),f=mv_makeFullNode(b,"th",{"class":"identify",colspan:1},h.photo_title.replace(/'/g,"")),mv_appendNode(f,e,g));if(mv_oExists(d.data))try{var l=h.photo_file_url,l=l.replace("mini_square","medium"),k=c?'<img class="imgTable" src="'+l+'" alt="" title="">':'<a href="'+h.photo_url+'" target="panoramio"><img class="imgTable" src="'+
l+'" alt="" title=""></a>';mv_writeTRTDs(b,g,{"class":"identifyPic",colspan:1},Array(k));c||(k='<span style="display: block; float: left"><a href="'+h.photo_url+'" target="panoramio">'+h.photo_title.replace(/'/g,"")+"</a></span>",mv_writeTRTDs(b,g,{"class":"identify identifyNoBorder",colspan:1},Array(k)));k=c?'<span style="text-align: left; display: block; float: left">by:'+h.owner_name+"</span>":'<span style="text-align: left; display: block; float: left">by: <a href="'+h.owner_url+'" target="panoramio">'+
h.owner_name+"</a></span>";mv_writeTRTDs(b,g,{"class":"identify identifyNoBorder",colspan:1},Array(k))}catch(n){}a.appendChild(g);return a}function mv_getWikipediaLayerBB(){mv_removeSVGele("WikiLayer");var a=dijit.byId("MVtoolbar.wikipedia").checked,b=mv_Map.Layers.getLayerByType("WikipediaLayer");mv_changeLayerVis2(a,b,!0)}
function mv_getWikipediaLayerNB(a,b,c){mv_removeSVGele("WikiLayer");b=mv_getDataObj(c,"gpx");if(0!=mv_oExists(b)){c=b.VB.centerP();var d=mv_Map.getRealMapY(b.VB.YMin()),e=mv_Map.getRealMapY(b.VB.Y),f=mv_Map.getRealMapX(b.VB.X),g=mv_Map.getRealMapX(b.VB.XMax());b=mv_calcLengthLatLng(d,f,d,g);b=Math.max(mv_calcLengthLatLng(e,f,e,g),b);b=Math.max(mv_calcLengthLatLng(d,f,e,f),b);b=b/2/1E3;d=mv_Map.getRealMapX(c.x);c=mv_Map.getRealMapY(c.y);e=mv_Map.Layers.getLayerByType("WikipediaLayer");mv_changeLayerVis2(!1,
e,!1);mv_doWikipediaNB(a,d,c,b)}}function mv_doWikipediaNB(a,b,c,d){(new MV.WebService({URL:"http://api.geonames.org/findNearbyWikipediaJSON"})).fire({lat:c,lng:b,radius:d,lang:a,maxRows:500,username:"mappetizer"},mv_insertWikiLayer,mv_errorWikipedia)}
function mv_doWikipediaBB(a){a=mv_Map.getMapViewbox("WebMercator"==mv_Map.Projection?!0:!1);try{(new MV.WebService({URL:"http://api.geonames.org/wikipediaBoundingBoxJSON"})).fire({north:a.Y,south:a.YMin(),east:a.XMax(),west:a.X,lang:mv_Doc.WikiLang,maxRows:mv_Map.WikiRows,username:"mappetizer"},mv_insertWikiLayer,mv_errorWikipedia)}catch(b){}}function mv_errorWikipedia(){window.status="Error when retrieving Wikipedia data from GeoNames Server!"}
function mv_insertWikiLayer(a,b){var c=mv_Map.Layers.getLayerByType("WikipediaLayer").id,d=mv_Map.Root.getElementById(c),e=null;if(mv_oExists(a))for(var f in a)e=a[f];if(0!=mv_oExists(e)){mv_XMLFileArray[c]=new MV.List;mv_removeSVGele("WikiLayer");f=mv_makeSVGNode(mv_Map.Root,"g",{id:"WikiLayer"});for(var g=mv_Map.CurrentVB.Width/mv_Map.CurrentExt.Width*18,h,l=0;l<mv_Map.Identifys.length();++l){var k=mv_Map.Identifys.List[l].data,n=!0;if(mv_oExists(k)&&"MV.JsonObject"==k.declaredClass){for(h=0;h<
e.length;h++)if(k.data.wikipediaUrl==e[h].wikipediaUrl){n=!1;break}n&&(mv_XMLFileArray[c].addMe(k),h=mv_LoadedPOIsSettings(k,g,"wiki"),f.appendChild(h))}}for(l=0;l<e.length;l++){k=e[l];h=mv_Map.getMapviewY(k.lat)-g/2;var p=mv_Map.getMapviewX(k.lng)-g/2,m=k.title.replace(/'/g,""),n=c+"rec"+k.wikipediaUrl.replace(/_/g,"");h=(new MV.Symbol({shape:"img",src:"symbols/wikipedia.png",width:g,height:g})).makeSVGNode(mv_Map.Root,1,{id:n,x:p,y:h,onmouseover:"parent.mv_mapTipOver(evt,'"+m+"');"});f.appendChild(h);
k=new MV.JsonObject({id:n,themaId:c,data:k,ele:h});mv_XMLFileArray[c].addMe(k)}d.appendChild(f);window.status=""}}function mv_LoadedPOIsSettings(a,b,c){var d=a.ele;a=a.data;"wiki"==c?(c=mv_Map.getMapviewY(a.lat)-b/2,b=mv_Map.getMapviewX(a.lng)-b/2):(c=mv_Map.getMapviewY(a.latitude)-b/2,b=mv_Map.getMapviewX(a.longitude)-b/2);0==isNaN(c)&0==isNaN(b)&&mv_setAttrSVG(d,{x:b,y:c});return d}
function mv_makeIdentifyWikiNode(a,b,c,d){var e=d.data;d=mv_makeNode(b,"table",{"class":"identify"});var f={"class":"identify"};if(c){c=mv_makeNode(b,"tr",{});var g=mv_makeFullNode(b,"th",f,e.title);mv_appendNode(g,c,d)}mv_oExists(e.thumbnailImg)&&(g=mv_makeNode(b,"img",{src:e.thumbnailImg,alt:e.title}),mv_writeTRTDs(b,d,f,Array(g)));mv_writeTRTDs(b,d,f,Array(e.summary));e=e.wikipediaUrl+";"+mv_Doc.getText("WikiUrl","Wikipedia");"http:"!=e.substr(0,5).toLowerCase()&&(e="http://"+e);e=mv_writeLink(e,
b,"","");mv_writeTRTDs(b,d,f,Array(e));a.appendChild(d);return a}function mv_makeIdentifyJsonNode(a,b,c,d){for(var e in d);}function mv_loadJSONDoc(a,b,c,d){window.status="Loading file, please wait ...";return dojo.io.script.get({url:a,timeout:5E3,callbackParamName:"callback",content:b,load:c,error:d})}function mv_loadJSONDoc2(a,b){window.status="Loading file, please wait ...";return dojo.io.script.get({url:a,content:b})}
function mv_zoomToLatLng(a,b,c,d){a=mv_Map.getMapviewX(parseFloat(a));b=mv_Map.getMapviewX(parseFloat(b));c=mv_Map.getMapviewY(parseFloat(c));d=mv_Map.getMapviewY(parseFloat(d));mv_zoomToExtent(a,b,d,c,20)}function mv_testDeviceLoation(){return navigator.geolocation?!0:(mv_alert("This application needs 'Location-Aware Browsing' to make sense for you!"),!1)}
function mv_geoGetCurPos(a){navigator.geolocation&&navigator.geolocation.getCurrentPosition(a,mv_errorDeviceLocationReturnAlert,mv_getLocationOption())}function mv_getLocationOption(){return{enableHighAccuracy:!0,timeout:1E4,maximumAge:0}}function mv_getDeviceLocation(){mv_geoGetCurPos(mv_callDeviceLocation)}
function mv_zoomToDeviceLocation(a,b){null!=mv_Map.Root.getElementById("mvDevicePoint")?(mv_removeSVGele("mvDevicePoint"),0==mv_oExists(b)&&(a=dijit.byId("MVtoolbar.zoomlocation"),b="none"),mv_setToggleButtonStyle(a,!0,{pressed:"#D3D3D3",unpressed:b})):mv_geoGetCurPos(mv_callZoomToDeviceLocation)}function mv_routeDeviceLocation_Poi(a,b,c){var d=dijit.byId("MVrouteContainer");mv_oExists(d)&&0==d.open&&d.toggle();mv_Doc.Para=[a,b,c];mv_geoGetCurPos(mv_callRoutingDeviceLocation_Poi)}
function mv_zoomToDeviceLocation_Poi(a){var b=a.split(",");a=parseFloat(b[0]);var c=parseFloat(b[2]),d=parseFloat(b[1])-a,b=parseFloat(b[3])-c;mv_Doc.Para=[a,c,d,b];mv_geoGetCurPos(mv_callzoomToDeviceLocation_Poi)}function mv_errorDeviceLocationReturnAlert(a){a=mv_errorDeviceLocation(a);mv_alert(a)}
function mv_errorDeviceLocation(a){switch(a.code){case a.PERMISSION_DENIED:return"Location not provided.";case a.POSITION_UNAVAILABLE:return"Current location not available.";case a.TIMEOUT:return"Retrieving position timed out.";default:return"unknown error."}}function mv_callRoutingDeviceLocation_Poi(a){mv_OSMNominatim.doRouting2(a.coords.latitude,a.coords.longitude,mv_Doc.Para[0],mv_Doc.Para[1],mv_Doc.Para[2])}
function mv_callDeviceLocationNominatim(a){mv_OSMNominatim.doReverseGeocoding(a.coords.latitude,a.coords.longitude)}function mv_errorDeviceLocationNominatim(a){a=mv_errorDeviceLocation(a);mv_alert(a+" This application takes uismedia home coordinates instead...");mv_OSMNominatim.doReverseGeocoding(48.003961,9.623895)}function mv_callDeviceLocation(a){a=mv_getDevicePoint(a);mv_Map.CurrentVB.pointWithIn(a)&&mv_drawDeviceLocation(a.x,a.y,!1)}
function mv_callZoomToDeviceLocation(a){var b={pressed:"#D3D3D3",unpressed:"#f8f8ba"},c=dijit.byId("MVtbSmartphone.zoomlocation");mv_setToggleButtonStyle(c,!1,b);c=dijit.byId("MVtoolbar.zoomlocation");mv_setToggleButtonStyle(c,!1,b);a=mv_getDevicePoint(a);0==mv_Map.DefaultVB.pointWithIn(a)&&mv_alert(mv_Doc.getText("OutsideApp","Hint: Your current location is outside of the map application"));mv_drawDeviceLocation(a.x,a.y,!0)}
function mv_callzoomToDeviceLocation_Poi(a){var b=new MV.Viewbox(mv_Doc.Para),c=b.centerP();a=mv_getDevicePoint(a);var d=new MV.Viewbox(a);b.union(d);mv_zoomToExtent2(b.getVBString(20));mv_drawDeviceLocation(a.x,a.y,!1);mv_drawPoiLocation(c.x,c.y,!1);mv_Doc.setMapTab()}function mv_getDevicePoint(a){var b=mv_Map.getMapviewX(a.coords.longitude);a=mv_Map.getMapviewY(a.coords.latitude);return new MV.Point(b,a)}
function mv_drawPoiLocation(a,b,c){var d=new MV.Symbol({shape:"img",src:"symbols/location2.png",width:26,height:26});a=mv_drawPoint("mvPoiPoint",!1,a,b,d);0==c&&a.setAttributeNS(null,"pointer-events","none")}function mv_drawDeviceLocation(a,b,c){var d=new MV.Symbol({shape:"img",src:"symbols/location.png",width:26,height:26});c&&mv_zoomToExtent(a,a,b,b,20);mv_drawPoint("mvDevicePoint",!1,a,b,d,mv_Doc.getText("CurrentPosition","current position"))}
function mv_declareClassMultilingualism(){dojo.declare("MV.JSONTextSettings",null,{Texts:null,IsLoaded:!1,constructor:function(a){this.Texts=mv_loadXMLDoc(a,"json")},getText:function(a,b){try{return eval("this.Texts."+a+"[mv_Doc.Lang]")}catch(c){return b}},getIcon:function(a){for(var b in this.Texts.OSMMapFeatures)for(var c in this.Texts.OSMMapFeatures[b])if(a==c)try{return this.Texts.OSMMapFeatures[b][c].img}catch(d){return""}return""},search:function(a,b){for(var c in this.Texts.OSMMapFeatures)for(var d in this.Texts.OSMMapFeatures[c])if(a==
d)try{return this.Texts.OSMMapFeatures[c][d][mv_Doc.Lang]}catch(e){return b}return b}})}function mv_getXMLTextValue(a,b){try{return dojo.trim(a.selectSingleNode(mv_Doc.Lang).firstChild.nodeValue)}catch(c){try{return dojo.trim(a.selectSingleNode(mv_Doc.DefLang).firstChild.nodeValue)}catch(d){try{return dojo.trim(a.firstChild.nodeValue)}catch(e){return b}}}}
function mv_timeStampToDate(a,b){var c=new Date,d=a;if(0<=a.indexOf(":")){d=a.slice(a.indexOf(b)+1);-1!=d.indexOf("Z")&&(d=d.substring(0,d.indexOf("Z")));var e=d.split(":");2==e.length&&e.push("0");mv_convertArray(e);c.setHours(e[0],e[1],e[2])}-1!=a.indexOf(b)&&(d=a.slice(0,a.indexOf(b)));d=d.split("-");mv_convertArray(d);c.setFullYear(d[0],d[1]-1,d[2]);return c}function mv_convertArray(a){for(var b=0;b<a.length;b++)isNaN(a[b])?a[b]=parseInt(a[b]):a[b]=Number(a[b])};